/**
 * ETF Hub catalog — a curated directory of the most in-demand US-listed ETFs,
 * organized into browseable categories (each a sub-page under /etfs/[id]) and
 * subgroups within them. Selection favors the funds people actually trade and
 * hold: the AUM/volume leaders of each niche, not an exhaustive registry.
 *
 * Static product data (tickers + names are public facts) — no analysis here;
 * live returns come from the shared closes seam at render time.
 */

export interface Etf {
    symbol: string;
    name: string;
}

export interface EtfGroup {
    id: string;
    label: string;
    blurb: string;
    etfs: Etf[];
}

export interface EtfCategory {
    id: string;
    label: string;
    /** One-line card/hub description. */
    blurb: string;
    /** Longer sub-page intro. */
    intro: string;
    /** Accent classes, following the Learn category palette grammar. */
    text: string;
    chip: string;
    grad: string;
    /** Optional cautionary note rendered on the sub-page. */
    caution?: string;
    groups: EtfGroup[];
}

const e = (symbol: string, name: string): Etf => ({ symbol, name });

export const ETF_CATEGORIES: EtfCategory[] = [
    {
        id: 'us-equity',
        label: 'US Equity',
        blurb: 'The core building blocks — S&P 500, total market, Nasdaq, size and style.',
        intro:
            'Broad US stock market exposure, from mega-cap indexes to micro-caps and the growth/value style split. These are the highest-volume ETFs in the world and the usual core of a portfolio.',
        text: 'text-sky-400',
        chip: 'bg-sky-400/10 text-sky-400',
        grad: 'from-sky-500/30 to-sky-500/5',
        groups: [
            {
                id: 'sp500',
                label: 'S&P 500',
                blurb: 'The benchmark — cap-weighted and equal-weighted flavors.',
                etfs: [
                    e('SPY', 'SPDR S&P 500 ETF Trust'),
                    e('IVV', 'iShares Core S&P 500 ETF'),
                    e('VOO', 'Vanguard S&P 500 ETF'),
                    e('SPLG', 'SPDR Portfolio S&P 500 ETF'),
                    e('RSP', 'Invesco S&P 500 Equal Weight ETF'),
                    e('OEF', 'iShares S&P 100 ETF'),
                    e('XLG', 'Invesco S&P 500 Top 50 ETF'),
                ],
            },
            {
                id: 'total-market',
                label: 'Total Market',
                blurb: 'Everything at once — the whole investable US market in one ticker.',
                etfs: [
                    e('VTI', 'Vanguard Total Stock Market ETF'),
                    e('ITOT', 'iShares Core S&P Total US Stock Market ETF'),
                    e('SCHB', 'Schwab US Broad Market ETF'),
                    e('SPTM', 'SPDR Portfolio S&P 1500 ETF'),
                    e('IWV', 'iShares Russell 3000 ETF'),
                    e('DFAC', 'Dimensional US Core Equity 2 ETF'),
                ],
            },
            {
                id: 'nasdaq-dow',
                label: 'Nasdaq & Dow',
                blurb: 'The tech-heavy Nasdaq-100 and the blue-chip Dow.',
                etfs: [
                    e('QQQ', 'Invesco QQQ Trust (Nasdaq-100)'),
                    e('QQQM', 'Invesco Nasdaq 100 ETF'),
                    e('ONEQ', 'Fidelity Nasdaq Composite Index ETF'),
                    e('DIA', 'SPDR Dow Jones Industrial Average ETF'),
                    e('MAGS', 'Roundhill Magnificent Seven ETF'),
                    e('MGC', 'Vanguard Mega Cap ETF'),
                    e('MGK', 'Vanguard Mega Cap Growth ETF'),
                ],
            },
            {
                id: 'growth-value',
                label: 'Growth & Value',
                blurb: 'The style split — large-cap growth vs. large-cap value.',
                etfs: [
                    e('VUG', 'Vanguard Growth ETF'),
                    e('IWF', 'iShares Russell 1000 Growth ETF'),
                    e('SCHG', 'Schwab US Large-Cap Growth ETF'),
                    e('SPYG', 'SPDR Portfolio S&P 500 Growth ETF'),
                    e('VTV', 'Vanguard Value ETF'),
                    e('IWD', 'iShares Russell 1000 Value ETF'),
                    e('SCHV', 'Schwab US Large-Cap Value ETF'),
                    e('SPYV', 'SPDR Portfolio S&P 500 Value ETF'),
                    e('MGV', 'Vanguard Mega Cap Value ETF'),
                ],
            },
            {
                id: 'mid-cap',
                label: 'Mid Cap',
                blurb: 'The middle of the market — S&P 400 and Russell mid-cap trackers.',
                etfs: [
                    e('VO', 'Vanguard Mid-Cap ETF'),
                    e('IJH', 'iShares Core S&P Mid-Cap ETF'),
                    e('MDY', 'SPDR S&P MidCap 400 ETF Trust'),
                    e('IWR', 'iShares Russell Mid-Cap ETF'),
                    e('VOT', 'Vanguard Mid-Cap Growth ETF'),
                    e('VOE', 'Vanguard Mid-Cap Value ETF'),
                ],
            },
            {
                id: 'small-micro',
                label: 'Small & Micro Cap',
                blurb: 'Russell 2000, S&P 600 and the smallest end of the market.',
                etfs: [
                    e('IWM', 'iShares Russell 2000 ETF'),
                    e('IJR', 'iShares Core S&P Small-Cap ETF'),
                    e('VB', 'Vanguard Small-Cap ETF'),
                    e('SCHA', 'Schwab US Small-Cap ETF'),
                    e('VIOO', 'Vanguard S&P Small-Cap 600 ETF'),
                    e('VBK', 'Vanguard Small-Cap Growth ETF'),
                    e('VBR', 'Vanguard Small-Cap Value ETF'),
                    e('IWO', 'iShares Russell 2000 Growth ETF'),
                    e('IWN', 'iShares Russell 2000 Value ETF'),
                    e('IWC', 'iShares Micro-Cap ETF'),
                ],
            },
        ],
    },
    {
        id: 'sector',
        label: 'Sectors & Industries',
        blurb: 'All 11 GICS sectors plus the industries traders actually rotate through.',
        intro:
            'The 11 US equity sectors via SPDR and Vanguard funds, plus the industry ETFs behind the big rotation trades — semiconductors, banks, biotech, homebuilders, energy services and more.',
        text: 'text-teal-400',
        chip: 'bg-teal-400/10 text-teal-400',
        grad: 'from-teal-500/30 to-teal-500/5',
        groups: [
            {
                id: 'spdr-sectors',
                label: 'SPDR Select Sectors',
                blurb: 'The classic XL-series — the most traded sector funds.',
                etfs: [
                    e('XLK', 'Technology Select Sector SPDR'),
                    e('XLF', 'Financial Select Sector SPDR'),
                    e('XLV', 'Health Care Select Sector SPDR'),
                    e('XLE', 'Energy Select Sector SPDR'),
                    e('XLI', 'Industrial Select Sector SPDR'),
                    e('XLY', 'Consumer Discretionary Select Sector SPDR'),
                    e('XLP', 'Consumer Staples Select Sector SPDR'),
                    e('XLU', 'Utilities Select Sector SPDR'),
                    e('XLB', 'Materials Select Sector SPDR'),
                    e('XLRE', 'Real Estate Select Sector SPDR'),
                    e('XLC', 'Communication Services Select Sector SPDR'),
                ],
            },
            {
                id: 'vanguard-sectors',
                label: 'Vanguard Sectors',
                blurb: 'The low-cost sector alternatives, broader than the S&P-only SPDRs.',
                etfs: [
                    e('VGT', 'Vanguard Information Technology ETF'),
                    e('VFH', 'Vanguard Financials ETF'),
                    e('VHT', 'Vanguard Health Care ETF'),
                    e('VDE', 'Vanguard Energy ETF'),
                    e('VIS', 'Vanguard Industrials ETF'),
                    e('VCR', 'Vanguard Consumer Discretionary ETF'),
                    e('VDC', 'Vanguard Consumer Staples ETF'),
                    e('VPU', 'Vanguard Utilities ETF'),
                    e('VAW', 'Vanguard Materials ETF'),
                    e('VOX', 'Vanguard Communication Services ETF'),
                ],
            },
            {
                id: 'tech-industries',
                label: 'Tech Industries',
                blurb: 'Semiconductors, software and the internet — the market’s engine room.',
                etfs: [
                    e('SMH', 'VanEck Semiconductor ETF'),
                    e('SOXX', 'iShares Semiconductor ETF'),
                    e('PSI', 'Invesco Semiconductors ETF'),
                    e('IGV', 'iShares Expanded Tech-Software ETF'),
                    e('FDN', 'First Trust Dow Jones Internet Index Fund'),
                    e('PNQI', 'Invesco Nasdaq Internet ETF'),
                ],
            },
            {
                id: 'financial-industries',
                label: 'Banks & Financials',
                blurb: 'Money-center banks, regionals, insurers and capital markets.',
                etfs: [
                    e('KBE', 'SPDR S&P Bank ETF'),
                    e('KRE', 'SPDR S&P Regional Banking ETF'),
                    e('KBWB', 'Invesco KBW Bank ETF'),
                    e('IAI', 'iShares US Broker-Dealers & Securities Exchanges ETF'),
                    e('KIE', 'SPDR S&P Insurance ETF'),
                ],
            },
            {
                id: 'health-industries',
                label: 'Biotech & Health Care',
                blurb: 'From large-cap biotech to devices, pharma and providers.',
                etfs: [
                    e('IBB', 'iShares Biotechnology ETF'),
                    e('XBI', 'SPDR S&P Biotech ETF'),
                    e('IHI', 'iShares US Medical Devices ETF'),
                    e('XPH', 'SPDR S&P Pharmaceuticals ETF'),
                    e('PPH', 'VanEck Pharmaceutical ETF'),
                    e('IHF', 'iShares US Healthcare Providers ETF'),
                ],
            },
            {
                id: 'industrial-industries',
                label: 'Industrials & Transport',
                blurb: 'Defense, transports, airlines — the real-economy pulse.',
                etfs: [
                    e('ITA', 'iShares US Aerospace & Defense ETF'),
                    e('PPA', 'Invesco Aerospace & Defense ETF'),
                    e('XAR', 'SPDR S&P Aerospace & Defense ETF'),
                    e('SHLD', 'Global X Defense Tech ETF'),
                    e('IYT', 'iShares US Transportation ETF'),
                    e('XTN', 'SPDR S&P Transportation ETF'),
                    e('JETS', 'US Global Jets ETF'),
                ],
            },
            {
                id: 'consumer-industries',
                label: 'Consumer & Housing',
                blurb: 'Homebuilders and retail — where the consumer cycle shows first.',
                etfs: [
                    e('XHB', 'SPDR S&P Homebuilders ETF'),
                    e('ITB', 'iShares US Home Construction ETF'),
                    e('XRT', 'SPDR S&P Retail ETF'),
                    e('BETZ', 'Roundhill Sports Betting & iGaming ETF'),
                    e('ESPO', 'VanEck Video Gaming and eSports ETF'),
                ],
            },
            {
                id: 'energy-materials-industries',
                label: 'Energy & Materials Industries',
                blurb: 'Drillers, servicers, miners and agribusiness.',
                etfs: [
                    e('XOP', 'SPDR S&P Oil & Gas Exploration & Production ETF'),
                    e('OIH', 'VanEck Oil Services ETF'),
                    e('XES', 'SPDR S&P Oil & Gas Equipment & Services ETF'),
                    e('XME', 'SPDR S&P Metals & Mining ETF'),
                    e('MOO', 'VanEck Agribusiness ETF'),
                ],
            },
        ],
    },
    {
        id: 'international',
        label: 'International & Regions',
        blurb: 'The world beyond the US — developed, emerging and single-country funds.',
        intro:
            'Global diversification in USD terms: all-world baskets, developed and emerging markets, regional blocks and the liquid single-country ETFs from Japan to Brazil.',
        text: 'text-violet-400',
        chip: 'bg-violet-400/10 text-violet-400',
        grad: 'from-violet-500/30 to-violet-500/5',
        groups: [
            {
                id: 'global',
                label: 'All-World & ex-US',
                blurb: 'One-ticket global equity, with or without the US.',
                etfs: [
                    e('VT', 'Vanguard Total World Stock ETF'),
                    e('ACWI', 'iShares MSCI ACWI ETF'),
                    e('URTH', 'iShares MSCI World ETF'),
                    e('VXUS', 'Vanguard Total International Stock ETF'),
                    e('IXUS', 'iShares Core MSCI Total International Stock ETF'),
                    e('VEU', 'Vanguard FTSE All-World ex-US ETF'),
                    e('ACWX', 'iShares MSCI ACWI ex US ETF'),
                ],
            },
            {
                id: 'developed',
                label: 'Developed Markets',
                blurb: 'Europe, Japan, Australia — the developed world ex-US.',
                etfs: [
                    e('EFA', 'iShares MSCI EAFE ETF'),
                    e('IEFA', 'iShares Core MSCI EAFE ETF'),
                    e('VEA', 'Vanguard FTSE Developed Markets ETF'),
                    e('SCHF', 'Schwab International Equity ETF'),
                    e('SPDW', 'SPDR Portfolio Developed World ex-US ETF'),
                    e('SCZ', 'iShares MSCI EAFE Small-Cap ETF'),
                    e('VSS', 'Vanguard FTSE All-World ex-US Small-Cap ETF'),
                ],
            },
            {
                id: 'emerging',
                label: 'Emerging Markets',
                blurb: 'The EM complex — broad, ex-China and small-cap flavors.',
                etfs: [
                    e('EEM', 'iShares MSCI Emerging Markets ETF'),
                    e('IEMG', 'iShares Core MSCI Emerging Markets ETF'),
                    e('VWO', 'Vanguard FTSE Emerging Markets ETF'),
                    e('SCHE', 'Schwab Emerging Markets Equity ETF'),
                    e('SPEM', 'SPDR Portfolio Emerging Markets ETF'),
                    e('EMXC', 'iShares MSCI Emerging Markets ex China ETF'),
                    e('FM', 'iShares Frontier and Select EM ETF'),
                ],
            },
            {
                id: 'europe',
                label: 'Europe',
                blurb: 'The continent broad and by country.',
                etfs: [
                    e('VGK', 'Vanguard FTSE Europe ETF'),
                    e('IEUR', 'iShares Core MSCI Europe ETF'),
                    e('EZU', 'iShares MSCI Eurozone ETF'),
                    e('FEZ', 'SPDR Euro Stoxx 50 ETF'),
                    e('HEDJ', 'WisdomTree Europe Hedged Equity Fund'),
                    e('EWG', 'iShares MSCI Germany ETF'),
                    e('EWU', 'iShares MSCI United Kingdom ETF'),
                    e('EWQ', 'iShares MSCI France ETF'),
                    e('EWL', 'iShares MSCI Switzerland ETF'),
                    e('EWI', 'iShares MSCI Italy ETF'),
                    e('EWP', 'iShares MSCI Spain ETF'),
                    e('EWN', 'iShares MSCI Netherlands ETF'),
                    e('EWD', 'iShares MSCI Sweden ETF'),
                    e('EPOL', 'iShares MSCI Poland ETF'),
                    e('GREK', 'Global X MSCI Greece ETF'),
                    e('TUR', 'iShares MSCI Turkey ETF'),
                ],
            },
            {
                id: 'asia',
                label: 'Asia-Pacific',
                blurb: 'Japan, China, India and the Asian tigers.',
                etfs: [
                    e('EWJ', 'iShares MSCI Japan ETF'),
                    e('DXJ', 'WisdomTree Japan Hedged Equity Fund'),
                    e('BBJP', 'JPMorgan BetaBuilders Japan ETF'),
                    e('MCHI', 'iShares MSCI China ETF'),
                    e('FXI', 'iShares China Large-Cap ETF'),
                    e('KWEB', 'KraneShares CSI China Internet ETF'),
                    e('ASHR', 'Xtrackers Harvest CSI 300 China A-Shares ETF'),
                    e('CQQQ', 'Invesco China Technology ETF'),
                    e('INDA', 'iShares MSCI India ETF'),
                    e('EPI', 'WisdomTree India Earnings Fund'),
                    e('INDY', 'iShares India 50 ETF'),
                    e('SMIN', 'iShares MSCI India Small-Cap ETF'),
                    e('EWT', 'iShares MSCI Taiwan ETF'),
                    e('EWY', 'iShares MSCI South Korea ETF'),
                    e('EWA', 'iShares MSCI Australia ETF'),
                    e('EWS', 'iShares MSCI Singapore ETF'),
                    e('EWH', 'iShares MSCI Hong Kong ETF'),
                    e('EWM', 'iShares MSCI Malaysia ETF'),
                    e('THD', 'iShares MSCI Thailand ETF'),
                    e('EIDO', 'iShares MSCI Indonesia ETF'),
                    e('EPHE', 'iShares MSCI Philippines ETF'),
                    e('VNM', 'VanEck Vietnam ETF'),
                    e('AAXJ', 'iShares MSCI All Country Asia ex Japan ETF'),
                    e('VPL', 'Vanguard FTSE Pacific ETF'),
                ],
            },
            {
                id: 'americas-mea',
                label: 'Americas, Middle East & Africa',
                blurb: 'North and Latin America plus the Gulf and Africa.',
                etfs: [
                    e('EWC', 'iShares MSCI Canada ETF'),
                    e('EWW', 'iShares MSCI Mexico ETF'),
                    e('EWZ', 'iShares MSCI Brazil ETF'),
                    e('ILF', 'iShares Latin America 40 ETF'),
                    e('ARGT', 'Global X MSCI Argentina ETF'),
                    e('ECH', 'iShares MSCI Chile ETF'),
                    e('KSA', 'iShares MSCI Saudi Arabia ETF'),
                    e('EIS', 'iShares MSCI Israel ETF'),
                    e('EZA', 'iShares MSCI South Africa ETF'),
                ],
            },
        ],
    },
    {
        id: 'bond',
        label: 'Bonds & Fixed Income',
        blurb: 'From T-bills to junk — the whole yield curve and credit spectrum.',
        intro:
            'Fixed income by duration and credit: cash-like T-bill funds, the treasury curve, TIPS, investment-grade and high-yield corporates, munis, mortgages and emerging-market debt.',
        text: 'text-amber-400',
        chip: 'bg-amber-400/10 text-amber-400',
        grad: 'from-amber-500/30 to-amber-500/5',
        groups: [
            {
                id: 'broad',
                label: 'Core & Aggregate',
                blurb: 'Total bond market in one ticker.',
                etfs: [
                    e('AGG', 'iShares Core US Aggregate Bond ETF'),
                    e('BND', 'Vanguard Total Bond Market ETF'),
                    e('IUSB', 'iShares Core Total USD Bond Market ETF'),
                    e('SCHZ', 'Schwab US Aggregate Bond ETF'),
                    e('BNDX', 'Vanguard Total International Bond ETF'),
                    e('BNDW', 'Vanguard Total World Bond ETF'),
                    e('BOND', 'PIMCO Active Bond ETF'),
                    e('TOTL', 'SPDR DoubleLine Total Return Tactical ETF'),
                ],
            },
            {
                id: 'cash',
                label: 'Cash & Ultra Short',
                blurb: 'T-bill and money-market-like funds — where idle cash earns.',
                etfs: [
                    e('SGOV', 'iShares 0-3 Month Treasury Bond ETF'),
                    e('BIL', 'SPDR Bloomberg 1-3 Month T-Bill ETF'),
                    e('SHV', 'iShares Short Treasury Bond ETF'),
                    e('USFR', 'WisdomTree Floating Rate Treasury Fund'),
                    e('TFLO', 'iShares Treasury Floating Rate Bond ETF'),
                    e('JPST', 'JPMorgan Ultra-Short Income ETF'),
                    e('MINT', 'PIMCO Enhanced Short Maturity Active ETF'),
                ],
            },
            {
                id: 'treasuries',
                label: 'Treasuries by Duration',
                blurb: 'The curve from 1-3 years out to 25+ year zeros.',
                etfs: [
                    e('SHY', 'iShares 1-3 Year Treasury Bond ETF'),
                    e('VGSH', 'Vanguard Short-Term Treasury ETF'),
                    e('SCHO', 'Schwab Short-Term US Treasury ETF'),
                    e('IEI', 'iShares 3-7 Year Treasury Bond ETF'),
                    e('IEF', 'iShares 7-10 Year Treasury Bond ETF'),
                    e('VGIT', 'Vanguard Intermediate-Term Treasury ETF'),
                    e('SCHR', 'Schwab Intermediate-Term US Treasury ETF'),
                    e('GOVT', 'iShares US Treasury Bond ETF'),
                    e('TLH', 'iShares 10-20 Year Treasury Bond ETF'),
                    e('TLT', 'iShares 20+ Year Treasury Bond ETF'),
                    e('VGLT', 'Vanguard Long-Term Treasury ETF'),
                    e('EDV', 'Vanguard Extended Duration Treasury ETF'),
                    e('ZROZ', 'PIMCO 25+ Year Zero Coupon US Treasury ETF'),
                ],
            },
            {
                id: 'tips',
                label: 'Inflation-Protected',
                blurb: 'TIPS — principal that adjusts with CPI.',
                etfs: [
                    e('TIP', 'iShares TIPS Bond ETF'),
                    e('VTIP', 'Vanguard Short-Term Inflation-Protected Securities ETF'),
                    e('SCHP', 'Schwab US TIPS ETF'),
                    e('STIP', 'iShares 0-5 Year TIPS Bond ETF'),
                ],
            },
            {
                id: 'corporate',
                label: 'Investment-Grade Corporate',
                blurb: 'The IG credit ladder, short to long.',
                etfs: [
                    e('LQD', 'iShares iBoxx $ Investment Grade Corporate Bond ETF'),
                    e('VCIT', 'Vanguard Intermediate-Term Corporate Bond ETF'),
                    e('VCSH', 'Vanguard Short-Term Corporate Bond ETF'),
                    e('VCLT', 'Vanguard Long-Term Corporate Bond ETF'),
                    e('IGSB', 'iShares 1-5 Year Investment Grade Corporate Bond ETF'),
                    e('IGIB', 'iShares 5-10 Year Investment Grade Corporate Bond ETF'),
                    e('USIG', 'iShares Broad USD Investment Grade Corporate Bond ETF'),
                    e('FLOT', 'iShares Floating Rate Bond ETF'),
                    e('JAAA', 'Janus Henderson AAA CLO ETF'),
                ],
            },
            {
                id: 'high-yield',
                label: 'High Yield & Loans',
                blurb: 'Junk bonds, fallen angels and leveraged loans.',
                etfs: [
                    e('HYG', 'iShares iBoxx $ High Yield Corporate Bond ETF'),
                    e('JNK', 'SPDR Bloomberg High Yield Bond ETF'),
                    e('USHY', 'iShares Broad USD High Yield Corporate Bond ETF'),
                    e('SHYG', 'iShares 0-5 Year High Yield Corporate Bond ETF'),
                    e('SJNK', 'SPDR Bloomberg Short Term High Yield Bond ETF'),
                    e('ANGL', 'VanEck Fallen Angel High Yield Bond ETF'),
                    e('BKLN', 'Invesco Senior Loan ETF'),
                    e('SRLN', 'SPDR Blackstone Senior Loan ETF'),
                ],
            },
            {
                id: 'muni-mortgage',
                label: 'Munis & Mortgages',
                blurb: 'Tax-exempt municipal bonds and agency MBS.',
                etfs: [
                    e('MUB', 'iShares National Muni Bond ETF'),
                    e('VTEB', 'Vanguard Tax-Exempt Bond ETF'),
                    e('SUB', 'iShares Short-Term National Muni Bond ETF'),
                    e('HYD', 'VanEck High Yield Muni ETF'),
                    e('MBB', 'iShares MBS ETF'),
                    e('VMBS', 'Vanguard Mortgage-Backed Securities ETF'),
                ],
            },
            {
                id: 'em-global',
                label: 'Emerging & Global Debt',
                blurb: 'Sovereign credit beyond the US, hard and local currency.',
                etfs: [
                    e('EMB', 'iShares JP Morgan USD Emerging Markets Bond ETF'),
                    e('VWOB', 'Vanguard Emerging Markets Government Bond ETF'),
                    e('EMLC', 'VanEck JP Morgan EM Local Currency Bond ETF'),
                    e('BWX', 'SPDR Bloomberg International Treasury Bond ETF'),
                    e('CWB', 'SPDR Bloomberg Convertible Securities ETF'),
                    e('ICVT', 'iShares Convertible Bond ETF'),
                ],
            },
        ],
    },
    {
        id: 'dividend',
        label: 'Dividend & Income',
        blurb: 'Getting paid to hold — dividend growth, high yield and option income.',
        intro:
            'Equity income in its main flavors: dividend growers, high-yielders, international payers, covered-call funds that convert volatility into monthly distributions, and preferreds.',
        text: 'text-emerald-400',
        chip: 'bg-emerald-400/10 text-emerald-400',
        grad: 'from-emerald-500/30 to-emerald-500/5',
        groups: [
            {
                id: 'growth',
                label: 'Dividend Growth',
                blurb: 'Companies that raise payouts year after year.',
                etfs: [
                    e('VIG', 'Vanguard Dividend Appreciation ETF'),
                    e('DGRO', 'iShares Core Dividend Growth ETF'),
                    e('DGRW', 'WisdomTree US Quality Dividend Growth Fund'),
                    e('NOBL', 'ProShares S&P 500 Dividend Aristocrats ETF'),
                    e('SDY', 'SPDR S&P Dividend ETF'),
                    e('RDVY', 'First Trust Rising Dividend Achievers ETF'),
                ],
            },
            {
                id: 'high-yield',
                label: 'High Dividend Yield',
                blurb: 'Maximum current income from equities.',
                etfs: [
                    e('SCHD', 'Schwab US Dividend Equity ETF'),
                    e('VYM', 'Vanguard High Dividend Yield ETF'),
                    e('HDV', 'iShares Core High Dividend ETF'),
                    e('DVY', 'iShares Select Dividend ETF'),
                    e('SPYD', 'SPDR Portfolio S&P 500 High Dividend ETF'),
                    e('SPHD', 'Invesco S&P 500 High Dividend Low Volatility ETF'),
                ],
            },
            {
                id: 'international',
                label: 'International Dividend',
                blurb: 'Foreign payers, developed and emerging.',
                etfs: [
                    e('IDV', 'iShares International Select Dividend ETF'),
                    e('VYMI', 'Vanguard International High Dividend Yield ETF'),
                    e('SCHY', 'Schwab International Dividend Equity ETF'),
                    e('DEM', 'WisdomTree Emerging Markets High Dividend Fund'),
                ],
            },
            {
                id: 'covered-call',
                label: 'Covered Call & Option Income',
                blurb: 'Selling options for monthly income — yield traded for upside.',
                etfs: [
                    e('JEPI', 'JPMorgan Equity Premium Income ETF'),
                    e('JEPQ', 'JPMorgan Nasdaq Equity Premium Income ETF'),
                    e('QYLD', 'Global X Nasdaq 100 Covered Call ETF'),
                    e('XYLD', 'Global X S&P 500 Covered Call ETF'),
                    e('RYLD', 'Global X Russell 2000 Covered Call ETF'),
                    e('DIVO', 'Amplify CWP Enhanced Dividend Income ETF'),
                    e('SPYI', 'NEOS S&P 500 High Income ETF'),
                    e('QQQI', 'NEOS Nasdaq-100 High Income ETF'),
                ],
            },
            {
                id: 'preferred',
                label: 'Preferred Stock',
                blurb: 'The hybrid layer — bond-like income from bank-heavy preferreds.',
                etfs: [
                    e('PFF', 'iShares Preferred & Income Securities ETF'),
                    e('PGX', 'Invesco Preferred ETF'),
                    e('PFFD', 'Global X US Preferred ETF'),
                ],
            },
        ],
    },
    {
        id: 'factor',
        label: 'Factors & Strategies',
        blurb: 'Momentum, quality, low-vol, cash flow — systematic tilts and hedges.',
        intro:
            'Rules-based tilts on the market: the classic factors (momentum, quality, value, low volatility), cash-flow screens, all-in-one allocation funds and the liquid-alternative strategies used as hedges.',
        text: 'text-indigo-400',
        chip: 'bg-indigo-400/10 text-indigo-400',
        grad: 'from-indigo-500/30 to-indigo-500/5',
        groups: [
            {
                id: 'classic-factors',
                label: 'Classic Factors',
                blurb: 'Momentum, quality and value, isolated.',
                etfs: [
                    e('MTUM', 'iShares MSCI USA Momentum Factor ETF'),
                    e('SPMO', 'Invesco S&P 500 Momentum ETF'),
                    e('QUAL', 'iShares MSCI USA Quality Factor ETF'),
                    e('SPHQ', 'Invesco S&P 500 Quality ETF'),
                    e('VLUE', 'iShares MSCI USA Value Factor ETF'),
                    e('RPV', 'Invesco S&P 500 Pure Value ETF'),
                    e('AVUV', 'Avantis US Small Cap Value ETF'),
                    e('AVDV', 'Avantis International Small Cap Value ETF'),
                    e('MOAT', 'VanEck Morningstar Wide Moat ETF'),
                    e('LRGF', 'iShares US Equity Factor ETF'),
                ],
            },
            {
                id: 'low-vol',
                label: 'Low Volatility',
                blurb: 'The defensive tilt — smoother rides in rough tape.',
                etfs: [
                    e('USMV', 'iShares MSCI USA Min Vol Factor ETF'),
                    e('SPLV', 'Invesco S&P 500 Low Volatility ETF'),
                    e('EFAV', 'iShares MSCI EAFE Min Vol Factor ETF'),
                    e('EEMV', 'iShares MSCI Emerging Markets Min Vol Factor ETF'),
                    e('ACWV', 'iShares MSCI Global Min Vol Factor ETF'),
                    e('SPHB', 'Invesco S&P 500 High Beta ETF'),
                ],
            },
            {
                id: 'cash-flow',
                label: 'Cash Flow & Shareholder Yield',
                blurb: 'Free-cash-flow screens and buyback tilts.',
                etfs: [
                    e('COWZ', 'Pacer US Cash Cows 100 ETF'),
                    e('CALF', 'Pacer US Small Cap Cash Cows 100 ETF'),
                    e('PKW', 'Invesco Buyback Achievers ETF'),
                    e('SYLD', 'Cambria Shareholder Yield ETF'),
                ],
            },
            {
                id: 'allocation',
                label: 'Allocation & Multi-Asset',
                blurb: 'Whole portfolios in one ticker — stocks and bonds pre-mixed.',
                etfs: [
                    e('AOA', 'iShares Core Aggressive Allocation ETF'),
                    e('AOR', 'iShares Core Growth Allocation ETF'),
                    e('AOM', 'iShares Core Moderate Allocation ETF'),
                    e('AOK', 'iShares Core Conservative Allocation ETF'),
                    e('NTSX', 'WisdomTree US Efficient Core Fund'),
                    e('SWAN', 'Amplify BlackSwan Growth & Treasury Core ETF'),
                    e('RPAR', 'RPAR Risk Parity ETF'),
                ],
            },
            {
                id: 'alternatives',
                label: 'Hedges & Liquid Alts',
                blurb: 'Managed futures, anti-beta and tail hedges — the crisis toolkit.',
                etfs: [
                    e('DBMF', 'iMGP DBi Managed Futures Strategy ETF'),
                    e('KMLM', 'KFA Mount Lucas Managed Futures Index Strategy ETF'),
                    e('CTA', 'Simplify Managed Futures Strategy ETF'),
                    e('BTAL', 'AGF US Market Neutral Anti-Beta Fund'),
                    e('MNA', 'IQ Merger Arbitrage ETF'),
                    e('TAIL', 'Cambria Tail Risk ETF'),
                    e('BUFR', 'First Trust Cboe Vest Fund of Buffer ETFs'),
                ],
            },
            {
                id: 'esg',
                label: 'ESG',
                blurb: 'Broad market with sustainability screens.',
                etfs: [
                    e('ESGU', 'iShares ESG Aware MSCI USA ETF'),
                    e('ESGV', 'Vanguard ESG US Stock ETF'),
                ],
            },
        ],
    },
    {
        id: 'thematic',
        label: 'Thematic & Innovation',
        blurb: 'AI, robotics, cyber, clean energy, space — the long-horizon themes.',
        intro:
            'Concentrated bets on structural change: artificial intelligence, cybersecurity, cloud, electrification, nuclear renaissance, genomics and the rest of the innovation complex. Higher octane than sector funds — size positions accordingly.',
        text: 'text-fuchsia-400',
        chip: 'bg-fuchsia-400/10 text-fuchsia-400',
        grad: 'from-fuchsia-500/30 to-fuchsia-500/5',
        groups: [
            {
                id: 'ai-robotics',
                label: 'AI & Robotics',
                blurb: 'The machines-that-learn trade.',
                etfs: [
                    e('BOTZ', 'Global X Robotics & Artificial Intelligence ETF'),
                    e('ROBO', 'ROBO Global Robotics & Automation Index ETF'),
                    e('AIQ', 'Global X Artificial Intelligence & Technology ETF'),
                    e('IRBO', 'iShares Robotics and Artificial Intelligence ETF'),
                    e('CHAT', 'Roundhill Generative AI & Technology ETF'),
                ],
            },
            {
                id: 'ark',
                label: 'ARK Innovation Suite',
                blurb: 'Cathie Wood’s actively managed disruption funds.',
                etfs: [
                    e('ARKK', 'ARK Innovation ETF'),
                    e('ARKW', 'ARK Next Generation Internet ETF'),
                    e('ARKG', 'ARK Genomic Revolution ETF'),
                    e('ARKQ', 'ARK Autonomous Technology & Robotics ETF'),
                    e('ARKF', 'ARK Fintech Innovation ETF'),
                    e('ARKX', 'ARK Space Exploration & Innovation ETF'),
                ],
            },
            {
                id: 'cyber-cloud',
                label: 'Cybersecurity & Cloud',
                blurb: 'The software infrastructure themes.',
                etfs: [
                    e('HACK', 'Amplify Cybersecurity ETF'),
                    e('CIBR', 'First Trust Nasdaq Cybersecurity ETF'),
                    e('BUG', 'Global X Cybersecurity ETF'),
                    e('SKYY', 'First Trust Cloud Computing ETF'),
                    e('WCLD', 'WisdomTree Cloud Computing Fund'),
                    e('CLOU', 'Global X Cloud Computing ETF'),
                ],
            },
            {
                id: 'fintech-commerce',
                label: 'Fintech & Digital Commerce',
                blurb: 'Payments, digital finance and online retail.',
                etfs: [
                    e('FINX', 'Global X FinTech ETF'),
                    e('IPAY', 'Amplify Digital Payments ETF'),
                    e('ONLN', 'ProShares Online Retail ETF'),
                    e('METV', 'Roundhill Ball Metaverse ETF'),
                ],
            },
            {
                id: 'energy-transition',
                label: 'Energy Transition',
                blurb: 'Solar, wind, batteries, EVs and hydrogen.',
                etfs: [
                    e('ICLN', 'iShares Global Clean Energy ETF'),
                    e('TAN', 'Invesco Solar ETF'),
                    e('FAN', 'First Trust Global Wind Energy ETF'),
                    e('QCLN', 'First Trust Nasdaq Clean Edge Green Energy Fund'),
                    e('PBW', 'Invesco WilderHill Clean Energy ETF'),
                    e('LIT', 'Global X Lithium & Battery Tech ETF'),
                    e('BATT', 'Amplify Lithium & Battery Technology ETF'),
                    e('DRIV', 'Global X Autonomous & Electric Vehicles ETF'),
                    e('HYDR', 'Global X Hydrogen ETF'),
                ],
            },
            {
                id: 'nuclear-space',
                label: 'Nuclear & Space',
                blurb: 'Uranium miners, utilities and the orbital economy.',
                etfs: [
                    e('URA', 'Global X Uranium ETF'),
                    e('URNM', 'Sprott Uranium Miners ETF'),
                    e('NLR', 'VanEck Uranium and Nuclear ETF'),
                    e('UFO', 'Procure Space ETF'),
                ],
            },
            {
                id: 'genomics-misc',
                label: 'Genomics & Frontier Themes',
                blurb: 'Biotech innovation and the smaller thematic niches.',
                etfs: [
                    e('GNOM', 'Global X Genomics & Biotechnology ETF'),
                    e('HERO', 'Global X Video Games & Esports ETF'),
                    e('MSOS', 'AdvisorShares Pure US Cannabis ETF'),
                    e('MJ', 'Amplify Alternative Harvest ETF'),
                ],
            },
        ],
    },
    {
        id: 'commodity',
        label: 'Commodities & Gold',
        blurb: 'Bullion, oil, gas, grains and the miners that dig them up.',
        intro:
            'Hard assets: physically-backed precious metals, energy futures funds, broad commodity baskets, agriculture and the gold/silver/copper miner equities that trade as leveraged plays on the metal.',
        text: 'text-orange-400',
        chip: 'bg-orange-400/10 text-orange-400',
        grad: 'from-orange-500/30 to-orange-500/5',
        groups: [
            {
                id: 'precious',
                label: 'Precious Metals',
                blurb: 'Physically-backed gold, silver, platinum and palladium.',
                etfs: [
                    e('GLD', 'SPDR Gold Shares'),
                    e('IAU', 'iShares Gold Trust'),
                    e('GLDM', 'SPDR Gold MiniShares Trust'),
                    e('SGOL', 'abrdn Physical Gold Shares ETF'),
                    e('SLV', 'iShares Silver Trust'),
                    e('SIVR', 'abrdn Physical Silver Shares ETF'),
                    e('PPLT', 'abrdn Physical Platinum Shares ETF'),
                    e('PALL', 'abrdn Physical Palladium Shares ETF'),
                ],
            },
            {
                id: 'miners',
                label: 'Miners',
                blurb: 'Gold, silver and copper producers — beta on the metal.',
                etfs: [
                    e('GDX', 'VanEck Gold Miners ETF'),
                    e('GDXJ', 'VanEck Junior Gold Miners ETF'),
                    e('SIL', 'Global X Silver Miners ETF'),
                    e('SILJ', 'Amplify Junior Silver Miners ETF'),
                    e('COPX', 'Global X Copper Miners ETF'),
                ],
            },
            {
                id: 'energy',
                label: 'Energy',
                blurb: 'Crude and natural gas futures exposure.',
                etfs: [
                    e('USO', 'United States Oil Fund'),
                    e('BNO', 'United States Brent Oil Fund'),
                    e('UNG', 'United States Natural Gas Fund'),
                ],
            },
            {
                id: 'broad',
                label: 'Broad Baskets',
                blurb: 'Diversified commodity exposure in one fund.',
                etfs: [
                    e('DBC', 'Invesco DB Commodity Index Tracking Fund'),
                    e('PDBC', 'Invesco Optimum Yield Diversified Commodity Strategy ETF'),
                    e('GSG', 'iShares S&P GSCI Commodity-Indexed Trust'),
                    e('FTGC', 'First Trust Global Tactical Commodity Strategy Fund'),
                    e('KRBN', 'KraneShares Global Carbon Strategy ETF'),
                ],
            },
            {
                id: 'agriculture',
                label: 'Agriculture & Metals',
                blurb: 'Grains, softs and industrial metals.',
                etfs: [
                    e('DBA', 'Invesco DB Agriculture Fund'),
                    e('CORN', 'Teucrium Corn Fund'),
                    e('WEAT', 'Teucrium Wheat Fund'),
                    e('SOYB', 'Teucrium Soybean Fund'),
                    e('CANE', 'Teucrium Sugar Fund'),
                    e('DBB', 'Invesco DB Base Metals Fund'),
                    e('CPER', 'United States Copper Index Fund'),
                ],
            },
        ],
    },
    {
        id: 'real-assets',
        label: 'Real Estate & Real Assets',
        blurb: 'REITs, infrastructure, water, timber and the midstream pipes.',
        intro:
            'The tangible economy: real estate investment trusts broad and specialized, the infrastructure build-out, water and timber funds, and energy midstream partnerships prized for their distributions.',
        text: 'text-cyan-400',
        chip: 'bg-cyan-400/10 text-cyan-400',
        grad: 'from-cyan-500/30 to-cyan-500/5',
        groups: [
            {
                id: 'reits',
                label: 'REITs',
                blurb: 'The broad US real estate market.',
                etfs: [
                    e('VNQ', 'Vanguard Real Estate ETF'),
                    e('SCHH', 'Schwab US REIT ETF'),
                    e('IYR', 'iShares US Real Estate ETF'),
                    e('USRT', 'iShares Core US REIT ETF'),
                    e('VNQI', 'Vanguard Global ex-US Real Estate ETF'),
                    e('REET', 'iShares Global REIT ETF'),
                ],
            },
            {
                id: 'specialized-reits',
                label: 'Specialized REITs',
                blurb: 'Data centers, industrial, residential and mortgage REITs.',
                etfs: [
                    e('SRVR', 'Pacer Data & Infrastructure Real Estate ETF'),
                    e('INDS', 'Pacer Industrial Real Estate ETF'),
                    e('REZ', 'iShares Residential and Multisector Real Estate ETF'),
                    e('REM', 'iShares Mortgage Real Estate ETF'),
                    e('MORT', 'VanEck Mortgage REIT Income ETF'),
                ],
            },
            {
                id: 'infrastructure',
                label: 'Infrastructure',
                blurb: 'Roads, rails, grids — the build-out trade.',
                etfs: [
                    e('PAVE', 'Global X US Infrastructure Development ETF'),
                    e('IFRA', 'iShares US Infrastructure ETF'),
                    e('IGF', 'iShares Global Infrastructure ETF'),
                ],
            },
            {
                id: 'water-timber',
                label: 'Water, Timber & Resources',
                blurb: 'Natural-resource equity plays.',
                etfs: [
                    e('PHO', 'Invesco Water Resources ETF'),
                    e('FIW', 'First Trust Water ETF'),
                    e('CGW', 'Invesco S&P Global Water Index ETF'),
                    e('WOOD', 'iShares Global Timber & Forestry ETF'),
                    e('CUT', 'Invesco MSCI Global Timber ETF'),
                    e('GUNR', 'FlexShares Global Upstream Natural Resources ETF'),
                ],
            },
            {
                id: 'midstream',
                label: 'MLPs & Midstream',
                blurb: 'Pipelines and energy infrastructure income.',
                etfs: [
                    e('AMLP', 'Alerian MLP ETF'),
                    e('EMLP', 'First Trust North American Energy Infrastructure Fund'),
                    e('MLPX', 'Global X MLP & Energy Infrastructure ETF'),
                ],
            },
        ],
    },
    {
        id: 'crypto',
        label: 'Crypto & Blockchain',
        blurb: 'Spot Bitcoin and Ether funds plus the blockchain equity complex.',
        intro:
            'Digital-asset exposure through regulated wrappers: the spot Bitcoin and Ethereum ETFs, futures-based strategies, and equities of exchanges, miners and blockchain builders.',
        text: 'text-rose-400',
        chip: 'bg-rose-400/10 text-rose-400',
        grad: 'from-rose-500/30 to-rose-500/5',
        caution:
            'Crypto trades around the clock while these funds price only during market hours, and the asset class is extremely volatile. Expect gaps and drawdowns far beyond equities.',
        groups: [
            {
                id: 'spot-btc',
                label: 'Spot Bitcoin',
                blurb: 'Physically-backed BTC in a brokerage account.',
                etfs: [
                    e('IBIT', 'iShares Bitcoin Trust ETF'),
                    e('FBTC', 'Fidelity Wise Origin Bitcoin Fund'),
                    e('ARKB', 'ARK 21Shares Bitcoin ETF'),
                    e('BITB', 'Bitwise Bitcoin ETF'),
                    e('GBTC', 'Grayscale Bitcoin Trust ETF'),
                    e('HODL', 'VanEck Bitcoin ETF'),
                    e('BTCO', 'Invesco Galaxy Bitcoin ETF'),
                ],
            },
            {
                id: 'spot-eth',
                label: 'Spot Ethereum',
                blurb: 'The ETH equivalents, approved mid-2024.',
                etfs: [
                    e('ETHA', 'iShares Ethereum Trust ETF'),
                    e('FETH', 'Fidelity Ethereum Fund'),
                    e('ETHW', 'Bitwise Ethereum ETF'),
                    e('ETHE', 'Grayscale Ethereum Trust ETF'),
                ],
            },
            {
                id: 'strategy',
                label: 'Futures & Strategy',
                blurb: 'Derivatives-based crypto exposure.',
                etfs: [e('BITO', 'ProShares Bitcoin Strategy ETF')],
            },
            {
                id: 'blockchain-equity',
                label: 'Blockchain Equity',
                blurb: 'Exchanges, miners and infrastructure stocks.',
                etfs: [
                    e('BLOK', 'Amplify Transformational Data Sharing ETF'),
                    e('BKCH', 'Global X Blockchain ETF'),
                    e('DAPP', 'VanEck Digital Transformation ETF'),
                    e('BITQ', 'Bitwise Crypto Industry Innovators ETF'),
                    e('WGMI', 'CoinShares Valkyrie Bitcoin Miners ETF'),
                ],
            },
        ],
    },
    {
        id: 'leveraged',
        label: 'Leveraged & Inverse',
        blurb: 'Daily 2x/3x bulls, bears and volatility — trading tools, not holdings.',
        intro:
            'Daily-reset leveraged and inverse funds on indexes, sectors, treasuries, volatility and single stocks. These compound daily returns, so they decay over time in choppy markets.',
        text: 'text-red-400',
        chip: 'bg-red-400/10 text-red-400',
        grad: 'from-red-500/30 to-red-500/5',
        caution:
            'Leveraged and inverse ETFs reset daily — held longer than a day, returns can diverge wildly from the index multiple, and volatility drag erodes them in sideways markets. Short-term trading instruments only.',
        groups: [
            {
                id: 'index-bull',
                label: 'Index Bulls',
                blurb: '2x and 3x long the major indexes.',
                etfs: [
                    e('TQQQ', 'ProShares UltraPro QQQ (3x)'),
                    e('QLD', 'ProShares Ultra QQQ (2x)'),
                    e('SPXL', 'Direxion Daily S&P 500 Bull 3X Shares'),
                    e('UPRO', 'ProShares UltraPro S&P 500 (3x)'),
                    e('SSO', 'ProShares Ultra S&P 500 (2x)'),
                    e('UDOW', 'ProShares UltraPro Dow30 (3x)'),
                    e('TNA', 'Direxion Daily Small Cap Bull 3X Shares'),
                    e('UWM', 'ProShares Ultra Russell2000 (2x)'),
                ],
            },
            {
                id: 'index-bear',
                label: 'Index Bears',
                blurb: 'Short the market, -1x to -3x.',
                etfs: [
                    e('SQQQ', 'ProShares UltraPro Short QQQ (-3x)'),
                    e('PSQ', 'ProShares Short QQQ (-1x)'),
                    e('QID', 'ProShares UltraShort QQQ (-2x)'),
                    e('SPXU', 'ProShares UltraPro Short S&P 500 (-3x)'),
                    e('SPXS', 'Direxion Daily S&P 500 Bear 3X Shares'),
                    e('SDS', 'ProShares UltraShort S&P 500 (-2x)'),
                    e('SH', 'ProShares Short S&P 500 (-1x)'),
                    e('SDOW', 'ProShares UltraPro Short Dow30 (-3x)'),
                    e('DOG', 'ProShares Short Dow30 (-1x)'),
                    e('TZA', 'Direxion Daily Small Cap Bear 3X Shares'),
                    e('RWM', 'ProShares Short Russell2000 (-1x)'),
                ],
            },
            {
                id: 'sector-lev',
                label: 'Sector Bulls & Bears',
                blurb: 'The 3x sector trades — semis, biotech, banks, energy.',
                etfs: [
                    e('SOXL', 'Direxion Daily Semiconductor Bull 3X Shares'),
                    e('SOXS', 'Direxion Daily Semiconductor Bear 3X Shares'),
                    e('LABU', 'Direxion Daily S&P Biotech Bull 3X Shares'),
                    e('LABD', 'Direxion Daily S&P Biotech Bear 3X Shares'),
                    e('FAS', 'Direxion Daily Financial Bull 3X Shares'),
                    e('FAZ', 'Direxion Daily Financial Bear 3X Shares'),
                    e('TECL', 'Direxion Daily Technology Bull 3X Shares'),
                    e('ERX', 'Direxion Daily Energy Bull 2X Shares'),
                    e('NUGT', 'Direxion Daily Gold Miners Bull 2X Shares'),
                    e('DUST', 'Direxion Daily Gold Miners Bear 2X Shares'),
                    e('DRN', 'Direxion Daily Real Estate Bull 3X Shares'),
                    e('DPST', 'Direxion Daily Regional Banks Bull 3X Shares'),
                    e('NAIL', 'Direxion Daily Homebuilders & Supplies Bull 3X Shares'),
                ],
            },
            {
                id: 'rates-vol',
                label: 'Treasuries & Volatility',
                blurb: 'Leveraged duration and the VIX complex.',
                etfs: [
                    e('TMF', 'Direxion Daily 20+ Year Treasury Bull 3X Shares'),
                    e('TMV', 'Direxion Daily 20+ Year Treasury Bear 3X Shares'),
                    e('TBT', 'ProShares UltraShort 20+ Year Treasury (-2x)'),
                    e('TBF', 'ProShares Short 20+ Year Treasury (-1x)'),
                    e('VXX', 'iPath Series B S&P 500 VIX Short-Term Futures ETN'),
                    e('UVXY', 'ProShares Ultra VIX Short-Term Futures ETF'),
                    e('VIXY', 'ProShares VIX Short-Term Futures ETF'),
                    e('SVXY', 'ProShares Short VIX Short-Term Futures ETF'),
                ],
            },
            {
                id: 'single-stock',
                label: 'Single-Stock Leverage',
                blurb: 'Daily 1.5x-2x long/short on the mega-caps.',
                etfs: [
                    e('TSLL', 'Direxion Daily TSLA Bull 2X Shares'),
                    e('TSLS', 'Direxion Daily TSLA Bear 1X Shares'),
                    e('NVDL', 'GraniteShares 2x Long NVDA Daily ETF'),
                    e('NVD', 'GraniteShares 2x Short NVDA Daily ETF'),
                    e('CONL', 'GraniteShares 2x Long COIN Daily ETF'),
                    e('MSTU', 'T-Rex 2X Long MSTR Daily Target ETF'),
                    e('MSTZ', 'T-Rex 2X Inverse MSTR Daily Target ETF'),
                    e('AAPU', 'Direxion Daily AAPL Bull 2X Shares'),
                    e('AMZU', 'Direxion Daily AMZN Bull 2X Shares'),
                    e('GGLL', 'Direxion Daily GOOGL Bull 2X Shares'),
                    e('MSFU', 'Direxion Daily MSFT Bull 2X Shares'),
                    e('FBL', 'GraniteShares 2x Long META Daily ETF'),
                ],
            },
            {
                id: 'crypto-lev',
                label: 'Crypto Leverage',
                blurb: 'Amplified and inverse Bitcoin exposure.',
                etfs: [
                    e('BITX', 'Volatility Shares 2x Bitcoin Strategy ETF'),
                    e('BITI', 'ProShares Short Bitcoin ETF'),
                    e('ETHU', 'Volatility Shares 2x Ether ETF'),
                ],
            },
        ],
    },
];

export function getEtfCategory(id: string): EtfCategory | undefined {
    return ETF_CATEGORIES.find((c) => c.id === id);
}

export function categoryEtfCount(cat: EtfCategory): number {
    return cat.groups.reduce((n, g) => n + g.etfs.length, 0);
}

export const TOTAL_ETF_COUNT = ETF_CATEGORIES.reduce((n, c) => n + categoryEtfCount(c), 0);

/** The hub spotlight — the most traded ETFs across all categories. */
export const SPOTLIGHT_ETFS: Etf[] = [
    e('SPY', 'S&P 500'),
    e('QQQ', 'Nasdaq-100'),
    e('IWM', 'Russell 2000'),
    e('EFA', 'Developed ex-US'),
    e('EEM', 'Emerging Markets'),
    e('TLT', '20+ Year Treasuries'),
    e('HYG', 'High Yield Credit'),
    e('GLD', 'Gold'),
    e('USO', 'Crude Oil'),
    e('IBIT', 'Bitcoin'),
];
