/**
 * Stock Hub catalog — curated lists of the most in-demand US-listed stocks and
 * ADRs, organized into browseable categories (sub-pages under
 * /stocks/lists/[id]) and subgroups. Mirrors the ETF Hub (lib/etfs.ts): static
 * product data only — tickers and names are public facts; live returns come
 * from the shared closes seam at render time.
 */

export interface ListedStock {
    symbol: string;
    name: string;
}

export interface StockGroup {
    id: string;
    label: string;
    blurb: string;
    stocks: ListedStock[];
}

export interface StockCategory {
    id: string;
    label: string;
    blurb: string;
    intro: string;
    text: string;
    chip: string;
    grad: string;
    caution?: string;
    groups: StockGroup[];
}

const s = (symbol: string, name: string): ListedStock => ({ symbol, name });

export const STOCK_CATEGORIES: StockCategory[] = [
    {
        id: 'mega-caps',
        label: 'Mega Caps',
        blurb: 'The trillion-dollar club and the blue chips that anchor every index.',
        intro:
            'The market’s heavyweights: the Magnificent Seven, the rest of the trillion-dollar tier and the Dow icons. These names set the tone for everything else.',
        text: 'text-sky-400',
        chip: 'bg-sky-400/10 text-sky-400',
        grad: 'from-sky-500/30 to-sky-500/5',
        groups: [
            {
                id: 'magnificent-7',
                label: 'Magnificent Seven',
                blurb: 'The mega-cap tech complex that drives index returns.',
                stocks: [
                    s('AAPL', 'Apple'),
                    s('MSFT', 'Microsoft'),
                    s('NVDA', 'NVIDIA'),
                    s('GOOGL', 'Alphabet'),
                    s('AMZN', 'Amazon'),
                    s('META', 'Meta Platforms'),
                    s('TSLA', 'Tesla'),
                ],
            },
            {
                id: 'trillion-tier',
                label: 'The Next Tier',
                blurb: 'The largest companies outside the Seven.',
                stocks: [
                    s('AVGO', 'Broadcom'),
                    s('LLY', 'Eli Lilly'),
                    s('JPM', 'JPMorgan Chase'),
                    s('V', 'Visa'),
                    s('WMT', 'Walmart'),
                    s('XOM', 'Exxon Mobil'),
                    s('UNH', 'UnitedHealth Group'),
                    s('MA', 'Mastercard'),
                    s('ORCL', 'Oracle'),
                    s('COST', 'Costco'),
                    s('HD', 'Home Depot'),
                    s('PG', 'Procter & Gamble'),
                    s('JNJ', 'Johnson & Johnson'),
                    s('NFLX', 'Netflix'),
                ],
            },
            {
                id: 'dow-icons',
                label: 'Dow Icons',
                blurb: 'The household names of the Dow Jones Industrial Average.',
                stocks: [
                    s('KO', 'Coca-Cola'),
                    s('MCD', "McDonald's"),
                    s('DIS', 'Walt Disney'),
                    s('IBM', 'IBM'),
                    s('CAT', 'Caterpillar'),
                    s('BA', 'Boeing'),
                    s('GS', 'Goldman Sachs'),
                    s('AXP', 'American Express'),
                    s('MMM', '3M'),
                    s('NKE', 'Nike'),
                ],
            },
        ],
    },
    {
        id: 'dividend',
        label: 'Dividend Stocks',
        blurb: 'Aristocrats, high yielders and the fastest dividend growers.',
        intro:
            'Equity income by style: the multi-decade dividend raisers, the highest sustainable yields among large caps, and the lower-yield names growing payouts fastest.',
        text: 'text-emerald-400',
        chip: 'bg-emerald-400/10 text-emerald-400',
        grad: 'from-emerald-500/30 to-emerald-500/5',
        groups: [
            {
                id: 'aristocrats',
                label: 'Aristocrat Stalwarts',
                blurb: 'Decades of uninterrupted dividend increases.',
                stocks: [
                    s('JNJ', 'Johnson & Johnson'),
                    s('PG', 'Procter & Gamble'),
                    s('KO', 'Coca-Cola'),
                    s('PEP', 'PepsiCo'),
                    s('MCD', "McDonald's"),
                    s('WMT', 'Walmart'),
                    s('CL', 'Colgate-Palmolive'),
                    s('KMB', 'Kimberly-Clark'),
                    s('ED', 'Consolidated Edison'),
                    s('ADP', 'Automatic Data Processing'),
                    s('LOW', "Lowe's"),
                    s('SYY', 'Sysco'),
                    s('GD', 'General Dynamics'),
                    s('EMR', 'Emerson Electric'),
                ],
            },
            {
                id: 'high-yield',
                label: 'High Yield',
                blurb: 'The big payers — telecom, tobacco, energy and monthly-dividend REITs.',
                stocks: [
                    s('VZ', 'Verizon'),
                    s('T', 'AT&T'),
                    s('MO', 'Altria'),
                    s('PM', 'Philip Morris International'),
                    s('O', 'Realty Income'),
                    s('KMI', 'Kinder Morgan'),
                    s('ENB', 'Enbridge'),
                    s('PFE', 'Pfizer'),
                    s('CVX', 'Chevron'),
                    s('XOM', 'Exxon Mobil'),
                ],
            },
            {
                id: 'dividend-growth',
                label: 'Dividend Growth',
                blurb: 'Lower yields today, double-digit payout growth.',
                stocks: [
                    s('AVGO', 'Broadcom'),
                    s('MSFT', 'Microsoft'),
                    s('V', 'Visa'),
                    s('MA', 'Mastercard'),
                    s('UNH', 'UnitedHealth Group'),
                    s('HD', 'Home Depot'),
                    s('ACN', 'Accenture'),
                    s('TXN', 'Texas Instruments'),
                    s('LIN', 'Linde'),
                ],
            },
        ],
    },
    {
        id: 'growth',
        label: 'Growth Stocks',
        blurb: 'The high-multiple names priced for expansion, from software to AI.',
        intro:
            'Companies the market pays up for: established large-cap compounders and the higher-octane software and platform names where growth is the whole thesis.',
        text: 'text-fuchsia-400',
        chip: 'bg-fuchsia-400/10 text-fuchsia-400',
        grad: 'from-fuchsia-500/30 to-fuchsia-500/5',
        groups: [
            {
                id: 'large-growth',
                label: 'Large-Cap Growth',
                blurb: 'Scaled businesses still compounding fast.',
                stocks: [
                    s('NVDA', 'NVIDIA'),
                    s('AVGO', 'Broadcom'),
                    s('NFLX', 'Netflix'),
                    s('CRM', 'Salesforce'),
                    s('ADBE', 'Adobe'),
                    s('NOW', 'ServiceNow'),
                    s('INTU', 'Intuit'),
                    s('UBER', 'Uber'),
                    s('BKNG', 'Booking Holdings'),
                    s('ABNB', 'Airbnb'),
                    s('SHOP', 'Shopify'),
                    s('MELI', 'MercadoLibre'),
                ],
            },
            {
                id: 'high-growth-software',
                label: 'High-Growth Software & AI',
                blurb: 'The premium-multiple cloud and AI names.',
                stocks: [
                    s('PLTR', 'Palantir'),
                    s('CRWD', 'CrowdStrike'),
                    s('PANW', 'Palo Alto Networks'),
                    s('SNOW', 'Snowflake'),
                    s('DDOG', 'Datadog'),
                    s('NET', 'Cloudflare'),
                    s('MDB', 'MongoDB'),
                    s('ZS', 'Zscaler'),
                    s('TTD', 'The Trade Desk'),
                    s('APP', 'AppLovin'),
                ],
            },
        ],
    },
    {
        id: 'value',
        label: 'Value & Quality',
        blurb: 'Cheap cash flows and durable compounders trading at sane multiples.',
        intro:
            'The other side of the style split: classic low-multiple value in banks, energy and autos, plus the quality industrial compounders that rarely go on sale.',
        text: 'text-amber-400',
        chip: 'bg-amber-400/10 text-amber-400',
        grad: 'from-amber-500/30 to-amber-500/5',
        groups: [
            {
                id: 'classic-value',
                label: 'Classic Value',
                blurb: 'Low multiples on real earnings.',
                stocks: [
                    s('JPM', 'JPMorgan Chase'),
                    s('BAC', 'Bank of America'),
                    s('WFC', 'Wells Fargo'),
                    s('C', 'Citigroup'),
                    s('CVX', 'Chevron'),
                    s('XOM', 'Exxon Mobil'),
                    s('VLO', 'Valero Energy'),
                    s('GM', 'General Motors'),
                    s('F', 'Ford'),
                    s('CMCSA', 'Comcast'),
                ],
            },
            {
                id: 'quality-compounders',
                label: 'Quality Compounders',
                blurb: 'Wide moats, steady returns on capital.',
                stocks: [
                    s('UNP', 'Union Pacific'),
                    s('HON', 'Honeywell'),
                    s('ADP', 'Automatic Data Processing'),
                    s('ITW', 'Illinois Tool Works'),
                    s('AJG', 'Arthur J. Gallagher'),
                    s('AON', 'Aon'),
                    s('WM', 'Waste Management'),
                    s('MCO', "Moody's"),
                    s('SPGI', 'S&P Global'),
                ],
            },
        ],
    },
    {
        id: 'tech',
        label: 'Technology',
        blurb: 'Software, hardware and the internet platforms.',
        intro:
            'The technology sector beyond the mega caps: enterprise software, the networking and hardware stack, and the consumer internet platforms.',
        text: 'text-indigo-400',
        chip: 'bg-indigo-400/10 text-indigo-400',
        grad: 'from-indigo-500/30 to-indigo-500/5',
        groups: [
            {
                id: 'software',
                label: 'Enterprise Software',
                blurb: 'The business-software franchises.',
                stocks: [
                    s('MSFT', 'Microsoft'),
                    s('ORCL', 'Oracle'),
                    s('SAP', 'SAP'),
                    s('CRM', 'Salesforce'),
                    s('ADBE', 'Adobe'),
                    s('NOW', 'ServiceNow'),
                    s('INTU', 'Intuit'),
                    s('WDAY', 'Workday'),
                    s('TEAM', 'Atlassian'),
                    s('HUBS', 'HubSpot'),
                ],
            },
            {
                id: 'hardware-networking',
                label: 'Hardware & Networking',
                blurb: 'The boxes and pipes of the AI build-out.',
                stocks: [
                    s('AAPL', 'Apple'),
                    s('ANET', 'Arista Networks'),
                    s('CSCO', 'Cisco Systems'),
                    s('DELL', 'Dell Technologies'),
                    s('SMCI', 'Super Micro Computer'),
                    s('HPQ', 'HP'),
                    s('STX', 'Seagate Technology'),
                    s('WDC', 'Western Digital'),
                ],
            },
            {
                id: 'internet',
                label: 'Internet Platforms',
                blurb: 'The consumer-attention businesses.',
                stocks: [
                    s('GOOGL', 'Alphabet'),
                    s('META', 'Meta Platforms'),
                    s('NFLX', 'Netflix'),
                    s('SPOT', 'Spotify'),
                    s('PINS', 'Pinterest'),
                    s('SNAP', 'Snap'),
                    s('RDDT', 'Reddit'),
                    s('DASH', 'DoorDash'),
                ],
            },
        ],
    },
    {
        id: 'semis-ai',
        label: 'Semiconductors & AI',
        blurb: 'The chip complex — designers, fabs and the equipment makers.',
        intro:
            'The center of the AI trade: GPU and chip designers, the foundries that fabricate them, the equipment monopolies upstream, and the power producers feeding the data centers.',
        text: 'text-violet-400',
        chip: 'bg-violet-400/10 text-violet-400',
        grad: 'from-violet-500/30 to-violet-500/5',
        groups: [
            {
                id: 'designers',
                label: 'Chip Designers',
                blurb: 'The fabless brains of the industry.',
                stocks: [
                    s('NVDA', 'NVIDIA'),
                    s('AMD', 'Advanced Micro Devices'),
                    s('AVGO', 'Broadcom'),
                    s('QCOM', 'Qualcomm'),
                    s('ARM', 'Arm Holdings'),
                    s('MRVL', 'Marvell Technology'),
                    s('ADI', 'Analog Devices'),
                    s('TXN', 'Texas Instruments'),
                    s('NXPI', 'NXP Semiconductors'),
                    s('ON', 'ON Semiconductor'),
                ],
            },
            {
                id: 'fabs-memory',
                label: 'Foundries & Memory',
                blurb: 'Where the chips actually get made.',
                stocks: [
                    s('TSM', 'Taiwan Semiconductor'),
                    s('INTC', 'Intel'),
                    s('MU', 'Micron Technology'),
                    s('GFS', 'GlobalFoundries'),
                ],
            },
            {
                id: 'equipment',
                label: 'Equipment & EDA',
                blurb: 'The toolmakers with near-monopolies.',
                stocks: [
                    s('ASML', 'ASML'),
                    s('AMAT', 'Applied Materials'),
                    s('LRCX', 'Lam Research'),
                    s('KLAC', 'KLA'),
                    s('SNPS', 'Synopsys'),
                    s('CDNS', 'Cadence Design Systems'),
                ],
            },
            {
                id: 'ai-power',
                label: 'AI Power & Infrastructure',
                blurb: 'The electricity behind the GPUs.',
                stocks: [
                    s('CEG', 'Constellation Energy'),
                    s('VST', 'Vistra'),
                    s('NRG', 'NRG Energy'),
                    s('ETN', 'Eaton'),
                    s('VRT', 'Vertiv'),
                ],
            },
        ],
    },
    {
        id: 'healthcare',
        label: 'Healthcare & Biotech',
        blurb: 'Pharma giants, biotech and the med-tech franchises.',
        intro:
            'The healthcare complex: big pharma and the GLP-1 leaders, large-cap biotech, and the devices, tools and services businesses that compound quietly underneath.',
        text: 'text-teal-400',
        chip: 'bg-teal-400/10 text-teal-400',
        grad: 'from-teal-500/30 to-teal-500/5',
        groups: [
            {
                id: 'pharma',
                label: 'Big Pharma',
                blurb: 'The global drugmakers.',
                stocks: [
                    s('LLY', 'Eli Lilly'),
                    s('NVO', 'Novo Nordisk'),
                    s('JNJ', 'Johnson & Johnson'),
                    s('MRK', 'Merck'),
                    s('ABBV', 'AbbVie'),
                    s('PFE', 'Pfizer'),
                    s('BMY', 'Bristol Myers Squibb'),
                    s('AZN', 'AstraZeneca'),
                    s('NVS', 'Novartis'),
                    s('GSK', 'GSK'),
                    s('SNY', 'Sanofi'),
                ],
            },
            {
                id: 'biotech',
                label: 'Biotech',
                blurb: 'Large-cap biotech and the gene-medicine pioneers.',
                stocks: [
                    s('AMGN', 'Amgen'),
                    s('GILD', 'Gilead Sciences'),
                    s('VRTX', 'Vertex Pharmaceuticals'),
                    s('REGN', 'Regeneron'),
                    s('MRNA', 'Moderna'),
                    s('BIIB', 'Biogen'),
                    s('ALNY', 'Alnylam Pharmaceuticals'),
                    s('BNTX', 'BioNTech'),
                ],
            },
            {
                id: 'devices-services',
                label: 'Devices, Tools & Services',
                blurb: 'Med-tech, diagnostics and managed care.',
                stocks: [
                    s('UNH', 'UnitedHealth Group'),
                    s('ISRG', 'Intuitive Surgical'),
                    s('ABT', 'Abbott Laboratories'),
                    s('MDT', 'Medtronic'),
                    s('TMO', 'Thermo Fisher Scientific'),
                    s('DHR', 'Danaher'),
                    s('SYK', 'Stryker'),
                    s('BSX', 'Boston Scientific'),
                    s('EW', 'Edwards Lifesciences'),
                    s('ELV', 'Elevance Health'),
                    s('CI', 'Cigna'),
                    s('CVS', 'CVS Health'),
                    s('HCA', 'HCA Healthcare'),
                ],
            },
        ],
    },
    {
        id: 'financial',
        label: 'Financials & Payments',
        blurb: 'Banks, brokers, payment rails and the alt-asset giants.',
        intro:
            'The money business: the big banks and brokers, the payments duopoly and fintech challengers, and the insurers and alternative-asset managers compounding behind them.',
        text: 'text-cyan-400',
        chip: 'bg-cyan-400/10 text-cyan-400',
        grad: 'from-cyan-500/30 to-cyan-500/5',
        groups: [
            {
                id: 'banks-brokers',
                label: 'Banks & Brokers',
                blurb: 'The balance-sheet businesses.',
                stocks: [
                    s('JPM', 'JPMorgan Chase'),
                    s('BAC', 'Bank of America'),
                    s('WFC', 'Wells Fargo'),
                    s('C', 'Citigroup'),
                    s('GS', 'Goldman Sachs'),
                    s('MS', 'Morgan Stanley'),
                    s('SCHW', 'Charles Schwab'),
                    s('USB', 'US Bancorp'),
                    s('PNC', 'PNC Financial'),
                    s('TFC', 'Truist Financial'),
                ],
            },
            {
                id: 'payments-fintech',
                label: 'Payments & Fintech',
                blurb: 'The rails and their challengers.',
                stocks: [
                    s('V', 'Visa'),
                    s('MA', 'Mastercard'),
                    s('AXP', 'American Express'),
                    s('PYPL', 'PayPal'),
                    s('FIS', 'Fidelity National Info Services'),
                    s('COIN', 'Coinbase'),
                    s('HOOD', 'Robinhood'),
                    s('SOFI', 'SoFi Technologies'),
                    s('AFRM', 'Affirm'),
                ],
            },
            {
                id: 'insurance-alts',
                label: 'Insurance & Alternative Assets',
                blurb: 'Underwriters and the private-markets giants.',
                stocks: [
                    s('BLK', 'BlackRock'),
                    s('BX', 'Blackstone'),
                    s('KKR', 'KKR'),
                    s('APO', 'Apollo Global Management'),
                    s('PGR', 'Progressive'),
                    s('CB', 'Chubb'),
                    s('TRV', 'Travelers'),
                    s('ALL', 'Allstate'),
                    s('MET', 'MetLife'),
                    s('AIG', 'AIG'),
                ],
            },
        ],
    },
    {
        id: 'consumer',
        label: 'Consumer',
        blurb: 'Discretionary spenders and the staples on every shelf.',
        intro:
            'Where households spend: retail, restaurants, travel and brands on the discretionary side; food, beverages and essentials on the defensive side.',
        text: 'text-orange-400',
        chip: 'bg-orange-400/10 text-orange-400',
        grad: 'from-orange-500/30 to-orange-500/5',
        groups: [
            {
                id: 'discretionary',
                label: 'Discretionary',
                blurb: 'Retail, restaurants, travel and brands.',
                stocks: [
                    s('AMZN', 'Amazon'),
                    s('HD', 'Home Depot'),
                    s('MCD', "McDonald's"),
                    s('NKE', 'Nike'),
                    s('SBUX', 'Starbucks'),
                    s('LOW', "Lowe's"),
                    s('TJX', 'TJX Companies'),
                    s('BKNG', 'Booking Holdings'),
                    s('ABNB', 'Airbnb'),
                    s('DIS', 'Walt Disney'),
                    s('CMG', 'Chipotle'),
                    s('LULU', 'Lululemon'),
                    s('RCL', 'Royal Caribbean'),
                    s('MAR', 'Marriott International'),
                ],
            },
            {
                id: 'staples',
                label: 'Staples',
                blurb: 'The defensive shelf — food, drink and essentials.',
                stocks: [
                    s('WMT', 'Walmart'),
                    s('COST', 'Costco'),
                    s('PG', 'Procter & Gamble'),
                    s('KO', 'Coca-Cola'),
                    s('PEP', 'PepsiCo'),
                    s('PM', 'Philip Morris International'),
                    s('MO', 'Altria'),
                    s('CL', 'Colgate-Palmolive'),
                    s('MDLZ', 'Mondelez'),
                    s('GIS', 'General Mills'),
                    s('KHC', 'Kraft Heinz'),
                    s('TGT', 'Target'),
                    s('KR', 'Kroger'),
                ],
            },
        ],
    },
    {
        id: 'industrial-defense',
        label: 'Industrials & Defense',
        blurb: 'Machinery, rails, logistics and the defense primes.',
        intro:
            'The real economy: heavy machinery, railroads and logistics, the electrical build-out, and the aerospace & defense complex from primes to new-space.',
        text: 'text-red-400',
        chip: 'bg-red-400/10 text-red-400',
        grad: 'from-red-500/30 to-red-500/5',
        groups: [
            {
                id: 'industrials',
                label: 'Core Industrials',
                blurb: 'Machinery, rails and logistics.',
                stocks: [
                    s('CAT', 'Caterpillar'),
                    s('DE', 'Deere'),
                    s('HON', 'Honeywell'),
                    s('GE', 'GE Aerospace'),
                    s('UNP', 'Union Pacific'),
                    s('UPS', 'UPS'),
                    s('FDX', 'FedEx'),
                    s('ETN', 'Eaton'),
                    s('PH', 'Parker Hannifin'),
                    s('EMR', 'Emerson Electric'),
                    s('URI', 'United Rentals'),
                    s('MMM', '3M'),
                ],
            },
            {
                id: 'defense',
                label: 'Aerospace & Defense',
                blurb: 'The primes and the disruptors.',
                stocks: [
                    s('BA', 'Boeing'),
                    s('LMT', 'Lockheed Martin'),
                    s('RTX', 'RTX'),
                    s('NOC', 'Northrop Grumman'),
                    s('GD', 'General Dynamics'),
                    s('LHX', 'L3Harris Technologies'),
                    s('TDG', 'TransDigm'),
                    s('HEI', 'HEICO'),
                    s('AXON', 'Axon Enterprise'),
                    s('RKLB', 'Rocket Lab'),
                ],
            },
        ],
    },
    {
        id: 'energy-materials',
        label: 'Energy, Materials & Utilities',
        blurb: 'Oil majors, miners, chemicals and the grid.',
        intro:
            'The commodity-linked equities: integrated oil and shale producers, the miners and chemical makers upstream of everything, and the utilities powering the grid.',
        text: 'text-yellow-400',
        chip: 'bg-yellow-400/10 text-yellow-400',
        grad: 'from-yellow-500/30 to-yellow-500/5',
        groups: [
            {
                id: 'oil-gas',
                label: 'Oil & Gas',
                blurb: 'Majors, shale and services.',
                stocks: [
                    s('XOM', 'Exxon Mobil'),
                    s('CVX', 'Chevron'),
                    s('COP', 'ConocoPhillips'),
                    s('EOG', 'EOG Resources'),
                    s('SLB', 'SLB'),
                    s('OXY', 'Occidental Petroleum'),
                    s('PSX', 'Phillips 66'),
                    s('MPC', 'Marathon Petroleum'),
                    s('VLO', 'Valero Energy'),
                    s('DVN', 'Devon Energy'),
                    s('FANG', 'Diamondback Energy'),
                    s('WMB', 'Williams Companies'),
                ],
            },
            {
                id: 'materials',
                label: 'Materials & Mining',
                blurb: 'Chemicals, metals and the miners.',
                stocks: [
                    s('LIN', 'Linde'),
                    s('APD', 'Air Products'),
                    s('SHW', 'Sherwin-Williams'),
                    s('FCX', 'Freeport-McMoRan'),
                    s('NEM', 'Newmont'),
                    s('NUE', 'Nucor'),
                    s('STLD', 'Steel Dynamics'),
                    s('ALB', 'Albemarle'),
                    s('DOW', 'Dow'),
                    s('DD', 'DuPont'),
                ],
            },
            {
                id: 'utilities',
                label: 'Utilities',
                blurb: 'The regulated grid and the merchant power upstarts.',
                stocks: [
                    s('NEE', 'NextEra Energy'),
                    s('DUK', 'Duke Energy'),
                    s('SO', 'Southern Company'),
                    s('D', 'Dominion Energy'),
                    s('AEP', 'American Electric Power'),
                    s('SRE', 'Sempra'),
                    s('EXC', 'Exelon'),
                    s('XEL', 'Xcel Energy'),
                ],
            },
        ],
    },
    {
        id: 'international-adrs',
        label: 'International ADRs',
        blurb: 'China tech, European champions and the global franchises on US exchanges.',
        intro:
            'The world’s companies traded in dollars: the Chinese internet platforms, Europe and Japan’s global champions, and the emerging-market leaders — all as US-listed ADRs.',
        text: 'text-violet-400',
        chip: 'bg-violet-400/10 text-violet-400',
        grad: 'from-violet-500/30 to-violet-500/5',
        groups: [
            {
                id: 'china',
                label: 'China ADRs',
                blurb: 'The Chinese internet and EV complex.',
                stocks: [
                    s('BABA', 'Alibaba'),
                    s('PDD', 'PDD Holdings'),
                    s('JD', 'JD.com'),
                    s('BIDU', 'Baidu'),
                    s('NTES', 'NetEase'),
                    s('NIO', 'NIO'),
                    s('XPEV', 'XPeng'),
                    s('LI', 'Li Auto'),
                    s('BILI', 'Bilibili'),
                    s('TME', 'Tencent Music'),
                    s('YUMC', 'Yum China'),
                ],
            },
            {
                id: 'europe-japan',
                label: 'Europe & Japan',
                blurb: 'The developed-world champions.',
                stocks: [
                    s('ASML', 'ASML'),
                    s('SAP', 'SAP'),
                    s('NVO', 'Novo Nordisk'),
                    s('AZN', 'AstraZeneca'),
                    s('SHEL', 'Shell'),
                    s('BP', 'BP'),
                    s('UL', 'Unilever'),
                    s('SONY', 'Sony'),
                    s('TM', 'Toyota Motor'),
                    s('HMC', 'Honda Motor'),
                    s('RIO', 'Rio Tinto'),
                    s('BHP', 'BHP Group'),
                ],
            },
            {
                id: 'emerging',
                label: 'Emerging Leaders',
                blurb: 'India, Latin America and Southeast Asia.',
                stocks: [
                    s('TSM', 'Taiwan Semiconductor'),
                    s('MELI', 'MercadoLibre'),
                    s('SE', 'Sea Limited'),
                    s('GRAB', 'Grab Holdings'),
                    s('INFY', 'Infosys'),
                    s('HDB', 'HDFC Bank'),
                    s('IBN', 'ICICI Bank'),
                    s('NU', 'Nu Holdings'),
                ],
            },
        ],
    },
    {
        id: 'reits',
        label: 'REITs',
        blurb: 'The listed landlords — towers, warehouses, data centers and malls.',
        intro:
            'Real estate investment trusts across property types: communication towers, logistics warehouses, data centers, self-storage, apartments and retail — the income real-asset layer of an equity portfolio.',
        text: 'text-lime-400',
        chip: 'bg-lime-400/10 text-lime-400',
        grad: 'from-lime-500/30 to-lime-500/5',
        groups: [
            {
                id: 'majors',
                label: 'The Majors',
                blurb: 'The largest REITs by market cap.',
                stocks: [
                    s('PLD', 'Prologis'),
                    s('AMT', 'American Tower'),
                    s('EQIX', 'Equinix'),
                    s('WELL', 'Welltower'),
                    s('SPG', 'Simon Property Group'),
                    s('O', 'Realty Income'),
                    s('PSA', 'Public Storage'),
                    s('DLR', 'Digital Realty'),
                    s('CCI', 'Crown Castle'),
                    s('VICI', 'VICI Properties'),
                ],
            },
            {
                id: 'residential-specialty',
                label: 'Residential & Specialty',
                blurb: 'Apartments, storage and niche property.',
                stocks: [
                    s('AVB', 'AvalonBay Communities'),
                    s('EQR', 'Equity Residential'),
                    s('INVH', 'Invitation Homes'),
                    s('EXR', 'Extra Space Storage'),
                    s('IRM', 'Iron Mountain'),
                    s('ARE', 'Alexandria Real Estate'),
                ],
            },
        ],
    },
    {
        id: 'crypto-stocks',
        label: 'Crypto Stocks',
        blurb: 'Exchanges, treasuries and miners — equity proxies for digital assets.',
        intro:
            'Stocks that trade as crypto proxies: the exchanges and brokers, the Bitcoin treasury companies, and the miners whose economics swing with the halving cycle.',
        text: 'text-rose-400',
        chip: 'bg-rose-400/10 text-rose-400',
        grad: 'from-rose-500/30 to-rose-500/5',
        caution:
            'These equities often move multiples of Bitcoin itself in both directions — treasury companies and miners are effectively leveraged crypto bets with equity risk on top.',
        groups: [
            {
                id: 'exchanges-treasury',
                label: 'Exchanges & Treasuries',
                blurb: 'Where crypto trades, and who hoards it.',
                stocks: [
                    s('COIN', 'Coinbase'),
                    s('HOOD', 'Robinhood'),
                    s('MSTR', 'Strategy (MicroStrategy)'),
                    s('GLXY', 'Galaxy Digital'),
                    s('CRCL', 'Circle Internet Group'),
                ],
            },
            {
                id: 'miners',
                label: 'Bitcoin Miners',
                blurb: 'Hashrate as a business model.',
                stocks: [
                    s('MARA', 'MARA Holdings'),
                    s('RIOT', 'Riot Platforms'),
                    s('CLSK', 'CleanSpark'),
                    s('CIFR', 'Cipher Mining'),
                    s('HUT', 'Hut 8'),
                    s('IREN', 'IREN'),
                ],
            },
        ],
    },
    {
        id: 'small-mid',
        label: 'Small & Mid Cap Favorites',
        blurb: 'The most-followed names outside the large-cap indexes.',
        intro:
            'Liquid, widely-followed small and mid caps — the consumer breakouts, the fintech and space disruptors, and the quantum moonshots retail watches daily.',
        text: 'text-pink-400',
        chip: 'bg-pink-400/10 text-pink-400',
        grad: 'from-pink-500/30 to-pink-500/5',
        caution:
            'Smaller companies swing harder than the indexes — wider spreads, bigger drawdowns and more single-headline risk. Position sizes should reflect that.',
        groups: [
            {
                id: 'consumer-breakouts',
                label: 'Consumer Breakouts',
                blurb: 'Fast-growing brands scaling nationally.',
                stocks: [
                    s('CAVA', 'CAVA Group'),
                    s('WING', 'Wingstop'),
                    s('CELH', 'Celsius Holdings'),
                    s('ELF', 'e.l.f. Beauty'),
                    s('DUOL', 'Duolingo'),
                    s('DKNG', 'DraftKings'),
                    s('TOST', 'Toast'),
                ],
            },
            {
                id: 'disruptors',
                label: 'Disruptors & Moonshots',
                blurb: 'Space, quantum and the high-beta story stocks.',
                stocks: [
                    s('RKLB', 'Rocket Lab'),
                    s('IONQ', 'IonQ'),
                    s('RGTI', 'Rigetti Computing'),
                    s('QBTS', 'D-Wave Quantum'),
                    s('OSCR', 'Oscar Health'),
                    s('HIMS', 'Hims & Hers Health'),
                    s('IOT', 'Samsara'),
                    s('GTLB', 'GitLab'),
                ],
            },
        ],
    },
];

export function getStockCategory(id: string): StockCategory | undefined {
    return STOCK_CATEGORIES.find((c) => c.id === id);
}

export function categoryStockCount(cat: StockCategory): number {
    return cat.groups.reduce((n, g) => n + g.stocks.length, 0);
}

export const TOTAL_LISTED_STOCK_COUNT = STOCK_CATEGORIES.reduce(
    (n, c) => n + categoryStockCount(c),
    0
);
