/**
 * Options strategy catalog — the structured data behind the Strategy Explorer,
 * comparison matrix, market-view filter and simulator. Each strategy is defined
 * by a leg builder (relative to spot) plus metadata; all payoff numbers are
 * computed by lib/options/payoff.ts, never hand-keyed. Educational only.
 */

import { roundStrike, type Leg } from './payoff';

export type Difficulty = 'Beginner' | 'Intermediate' | 'Advanced' | 'Professional';
export type View =
    | 'bullish'
    | 'bearish'
    | 'neutral'
    | 'high-vol'
    | 'low-vol'
    | 'income'
    | 'hedging'
    | 'capital-efficient';

export interface Strategy {
    slug: string;
    name: string;
    difficulty: Difficulty;
    /** 1 = lowest risk, 5 = highest. */
    risk: number;
    marketView: string;
    volView: string;
    income: boolean;
    hedge: boolean;
    views: View[];
    summary: string;
    construction: string[];
    bestEnv: string;
    worstEnv: string;
    advantages: string[];
    disadvantages: string[];
    mistakes: string[];
    assignment: string;
    timeDecay: string;
    related: string[];
    /** Build legs (premiums filled later by priceLegs) for a given spot. */
    build: (spot: number) => Leg[];
    /** True for multi-expiration strategies whose single-expiry payoff is N/A. */
    noPayoff?: boolean;
}

/** Strike helper: round (spot × (1+pct)) to a sensible increment. */
const K = (spot: number, pct: number) => roundStrike(spot * (1 + pct), spot);

export const STRATEGIES: Strategy[] = [
    {
        slug: 'long-call',
        name: 'Long Call',
        difficulty: 'Beginner',
        risk: 2,
        marketView: 'Bullish',
        volView: 'Rising / stable',
        income: false,
        hedge: false,
        views: ['bullish', 'high-vol', 'capital-efficient'],
        summary: 'Buy a call to profit from a rise with defined risk and leverage. Loss is capped at the premium; upside is unlimited.',
        construction: ['Buy 1 ATM call'],
        bestEnv: 'A strong, fairly quick move higher — ideally with rising implied volatility.',
        worstEnv: 'Sideways or falling price; time decay erodes the premium.',
        advantages: ['Defined, limited risk (the premium)', 'Unlimited upside with leverage', 'Far less capital than buying the stock'],
        disadvantages: ['Time decay works against you', 'Needs a move big enough to beat the premium', 'Can lose 100% of premium'],
        mistakes: ['Buying too little time to expiration', 'Overpaying when IV is already high', 'Treating it like a lottery ticket / oversizing'],
        assignment: 'None (you are the buyer).',
        timeDecay: 'Negative — every day costs you theta.',
        related: ['bull-call-spread', 'synthetic-long', 'protective-put'],
        build: (s) => [{ type: 'call', dir: 'long', strike: K(s, 0) }],
    },
    {
        slug: 'long-put',
        name: 'Long Put',
        difficulty: 'Beginner',
        risk: 2,
        marketView: 'Bearish',
        volView: 'Rising / stable',
        income: false,
        hedge: true,
        views: ['bearish', 'high-vol', 'hedging'],
        summary: 'Buy a put to profit from a decline (or hedge a holding) with defined risk. Loss capped at premium; profit grows as price falls.',
        construction: ['Buy 1 ATM put'],
        bestEnv: 'A sharp drop, often with a volatility spike.',
        worstEnv: 'Flat or rising price; theta bleeds the premium.',
        advantages: ['Defined, limited risk', 'Profits in a sell-off', 'Doubles as portfolio insurance'],
        disadvantages: ['Time decay against you', 'Markets drift up over time', 'Premium can expire worthless'],
        mistakes: ['Buying puts after IV has already spiked', 'Too little time to expiration', 'Using as a permanent hedge (costly drag)'],
        assignment: 'None (you are the buyer).',
        timeDecay: 'Negative — theta works against you.',
        related: ['protective-put', 'bear-put-spread', 'synthetic-short'],
        build: (s) => [{ type: 'put', dir: 'long', strike: K(s, 0) }],
    },
    {
        slug: 'covered-call',
        name: 'Covered Call',
        difficulty: 'Beginner',
        risk: 2,
        marketView: 'Neutral to mildly bullish',
        volView: 'Falling / stable',
        income: true,
        hedge: false,
        views: ['neutral', 'income', 'low-vol'],
        summary: 'Own 100 shares and sell a call against them for recurring premium. Caps upside at the strike in exchange for income and a small cushion.',
        construction: ['Own 100 shares', 'Sell 1 OTM call'],
        bestEnv: 'Flat to slowly rising stock you already own.',
        worstEnv: 'A sharp rally (capped gains) or a deep drop (stock losses).',
        advantages: ['Generates income on existing shares', 'Lowers cost basis', 'Defined obligation'],
        disadvantages: ['Caps upside above the strike', 'Full downside on the shares', 'Shares can be called away'],
        mistakes: ['Selling calls below your cost basis', 'Choosing strikes you would hate to sell at', 'Ignoring upcoming earnings/dividends'],
        assignment: 'Yes — shares may be called away if the call finishes ITM.',
        timeDecay: 'Positive — theta works for you (you are short the call).',
        related: ['cash-secured-put', 'collar', 'poor-mans-covered-call'],
        build: (s) => [
            { type: 'stock', dir: 'long' },
            { type: 'call', dir: 'short', strike: K(s, 0.05) },
        ],
    },
    {
        slug: 'cash-secured-put',
        name: 'Cash-Secured Put',
        difficulty: 'Beginner',
        risk: 2,
        marketView: 'Neutral to bullish',
        volView: 'Falling / stable',
        income: true,
        hedge: false,
        views: ['bullish', 'income', 'low-vol'],
        summary: 'Sell a put while holding cash to buy the shares if assigned. Earns premium and can let you buy a stock you want at a discount.',
        construction: ['Sell 1 OTM put', 'Hold cash to cover assignment'],
        bestEnv: 'A stock you would happily own, trading flat to up.',
        worstEnv: 'A deep decline well below the strike.',
        advantages: ['Income from premium', 'Effective entry below current price', 'Defined (cash-backed) obligation'],
        disadvantages: ['Large downside if the stock craters', 'Ties up cash/buying power', 'Capped profit (the premium)'],
        mistakes: ['Selling puts on stocks you do not want to own', 'Oversizing vs. account', 'Selling into earnings volatility unknowingly'],
        assignment: 'Yes — you may be required to buy shares at the strike.',
        timeDecay: 'Positive — you are short the put.',
        related: ['covered-call', 'bull-put-spread', 'jade-lizard'],
        build: (s) => [{ type: 'put', dir: 'short', strike: K(s, -0.05) }],
    },
    {
        slug: 'protective-put',
        name: 'Protective Put',
        difficulty: 'Beginner',
        risk: 1,
        marketView: 'Bullish but cautious',
        volView: 'Rising',
        income: false,
        hedge: true,
        views: ['hedging', 'bullish'],
        summary: 'Own shares and buy a put as insurance. Caps downside below the strike while keeping unlimited upside (minus the premium cost).',
        construction: ['Own 100 shares', 'Buy 1 OTM put'],
        bestEnv: 'You want to stay long through a risky event but cap the downside.',
        worstEnv: 'Calm markets — the insurance expires unused (a drag).',
        advantages: ['Hard floor on losses', 'Keeps full upside', 'Sleep-at-night insurance into events'],
        disadvantages: ['Premium is a recurring cost', 'Drags returns if never needed', 'Floor is below current price'],
        mistakes: ['Buying puts only after a drop (expensive)', 'Over-insuring constantly', 'Choosing a strike too far OTM to help'],
        assignment: 'None on the put you own; you may exercise it.',
        timeDecay: 'Negative on the put leg.',
        related: ['collar', 'long-put', 'long-call'],
        build: (s) => [
            { type: 'stock', dir: 'long' },
            { type: 'put', dir: 'long', strike: K(s, -0.05) },
        ],
    },
    {
        slug: 'collar',
        name: 'Collar',
        difficulty: 'Intermediate',
        risk: 1,
        marketView: 'Neutral, downside-protective',
        volView: 'Neutral',
        income: false,
        hedge: true,
        views: ['hedging', 'neutral', 'income'],
        summary: 'Own shares, buy a protective put and sell a call to finance it. Defines both a floor and a ceiling — often for little or no net cost.',
        construction: ['Own 100 shares', 'Buy 1 OTM put', 'Sell 1 OTM call'],
        bestEnv: 'Protecting gains in a holding you do not want to sell yet.',
        worstEnv: 'A big rally — upside is capped at the short call.',
        advantages: ['Downside floor, often near-free', 'Locks in a range', 'Great for concentrated/appreciated stock'],
        disadvantages: ['Caps upside', 'Shares can be called away', 'Limited profit band'],
        mistakes: ['Setting the ceiling too low', 'Forgetting dividends/earnings', 'Legging in at bad prices'],
        assignment: 'Yes — the short call can lead to shares being called away.',
        timeDecay: 'Roughly neutral (long put vs. short call offset).',
        related: ['protective-put', 'covered-call'],
        build: (s) => [
            { type: 'stock', dir: 'long' },
            { type: 'put', dir: 'long', strike: K(s, -0.05) },
            { type: 'call', dir: 'short', strike: K(s, 0.05) },
        ],
    },
    {
        slug: 'bull-call-spread',
        name: 'Bull Call Spread',
        difficulty: 'Intermediate',
        risk: 2,
        marketView: 'Moderately bullish',
        volView: 'Stable',
        income: false,
        hedge: false,
        views: ['bullish', 'capital-efficient'],
        summary: 'Buy a call and sell a higher call. Cheaper than a long call, with both profit and loss capped.',
        construction: ['Buy 1 ATM call', 'Sell 1 higher OTM call'],
        bestEnv: 'A measured move up to the short strike by expiration.',
        worstEnv: 'Price falls or stalls below the long strike.',
        advantages: ['Lower cost than a long call', 'Defined risk and reward', 'Less sensitive to IV'],
        disadvantages: ['Capped profit', 'Still loses if price falls', 'Two legs / commissions'],
        mistakes: ['Strikes too wide (no cheaper than a call)', 'Too little time', 'Ignoring the short-strike cap'],
        assignment: 'Low; possible on the short call if it goes deep ITM.',
        timeDecay: 'Mixed — mild once past the long strike.',
        related: ['long-call', 'bull-put-spread'],
        build: (s) => [
            { type: 'call', dir: 'long', strike: K(s, 0) },
            { type: 'call', dir: 'short', strike: K(s, 0.1) },
        ],
    },
    {
        slug: 'bull-put-spread',
        name: 'Bull Put Spread',
        difficulty: 'Intermediate',
        risk: 2,
        marketView: 'Neutral to bullish',
        volView: 'Falling / stable',
        income: true,
        hedge: false,
        views: ['bullish', 'income'],
        summary: 'Sell a put and buy a lower put for protection. A credit strategy that profits if the stock stays above the short strike.',
        construction: ['Sell 1 OTM put', 'Buy 1 lower OTM put'],
        bestEnv: 'Stock holds above the short put through expiration.',
        worstEnv: 'A drop below the long strike (max loss).',
        advantages: ['Collect a credit upfront', 'Defined risk', 'Profits from time decay'],
        disadvantages: ['Profit capped at the credit', 'Risk > reward typically', 'Assignment on the short put'],
        mistakes: ['Selling spreads too wide for the credit', 'Holding through max loss', 'Ignoring earnings'],
        assignment: 'Possible on the short put if ITM.',
        timeDecay: 'Positive — net short premium.',
        related: ['cash-secured-put', 'iron-condor', 'bull-call-spread'],
        build: (s) => [
            { type: 'put', dir: 'short', strike: K(s, -0.05) },
            { type: 'put', dir: 'long', strike: K(s, -0.15) },
        ],
    },
    {
        slug: 'bear-put-spread',
        name: 'Bear Put Spread',
        difficulty: 'Intermediate',
        risk: 2,
        marketView: 'Moderately bearish',
        volView: 'Stable',
        income: false,
        hedge: true,
        views: ['bearish', 'hedging', 'capital-efficient'],
        summary: 'Buy a put and sell a lower put. A cheaper, defined-risk way to play (or hedge) a decline.',
        construction: ['Buy 1 ATM put', 'Sell 1 lower OTM put'],
        bestEnv: 'A measured move down to the short strike.',
        worstEnv: 'Price rises or stalls above the long strike.',
        advantages: ['Cheaper than a long put', 'Defined risk and reward', 'Good event hedge'],
        disadvantages: ['Capped profit', 'Loses if price rises', 'Two legs'],
        mistakes: ['Strikes too wide', 'Too little time', 'Chasing after a drop'],
        assignment: 'Low; possible on the short put if deep ITM.',
        timeDecay: 'Mild net negative.',
        related: ['long-put', 'bear-call-spread'],
        build: (s) => [
            { type: 'put', dir: 'long', strike: K(s, 0) },
            { type: 'put', dir: 'short', strike: K(s, -0.1) },
        ],
    },
    {
        slug: 'bear-call-spread',
        name: 'Bear Call Spread',
        difficulty: 'Intermediate',
        risk: 2,
        marketView: 'Neutral to bearish',
        volView: 'Falling / stable',
        income: true,
        hedge: false,
        views: ['bearish', 'income'],
        summary: 'Sell a call and buy a higher call. A credit strategy that profits if the stock stays below the short strike.',
        construction: ['Sell 1 OTM call', 'Buy 1 higher OTM call'],
        bestEnv: 'Stock stays capped below the short call.',
        worstEnv: 'A rally above the long strike (max loss).',
        advantages: ['Upfront credit', 'Defined risk', 'Profits from time decay'],
        disadvantages: ['Profit capped at the credit', 'Risk > reward typically', 'Assignment risk'],
        mistakes: ['Selling into a strong uptrend', 'Spreads too wide', 'Holding to max loss'],
        assignment: 'Possible on the short call if ITM.',
        timeDecay: 'Positive — net short premium.',
        related: ['iron-condor', 'bear-put-spread'],
        build: (s) => [
            { type: 'call', dir: 'short', strike: K(s, 0.05) },
            { type: 'call', dir: 'long', strike: K(s, 0.15) },
        ],
    },
    {
        slug: 'iron-condor',
        name: 'Iron Condor',
        difficulty: 'Advanced',
        risk: 3,
        marketView: 'Neutral (range-bound)',
        volView: 'Falling',
        income: true,
        hedge: false,
        views: ['neutral', 'income', 'low-vol'],
        summary: 'Sell an OTM put spread and an OTM call spread. Profits when the stock stays inside a range; defined risk on both sides.',
        construction: ['Sell OTM put + buy lower put', 'Sell OTM call + buy higher call'],
        bestEnv: 'Range-bound stock with elevated IV that contracts.',
        worstEnv: 'A big move through either wing.',
        advantages: ['Income from both sides', 'Defined risk', 'High probability when wide'],
        disadvantages: ['Small profit vs. max loss', 'Four legs', 'Hurts on big moves'],
        mistakes: ['Wings too tight', 'Selling when IV is low', 'No plan to manage a tested side'],
        assignment: 'Possible on either short strike if breached.',
        timeDecay: 'Positive — net short premium.',
        related: ['iron-butterfly', 'short-strangle', 'bull-put-spread'],
        build: (s) => [
            { type: 'put', dir: 'short', strike: K(s, -0.05) },
            { type: 'put', dir: 'long', strike: K(s, -0.15) },
            { type: 'call', dir: 'short', strike: K(s, 0.05) },
            { type: 'call', dir: 'long', strike: K(s, 0.15) },
        ],
    },
    {
        slug: 'iron-butterfly',
        name: 'Iron Butterfly',
        difficulty: 'Advanced',
        risk: 3,
        marketView: 'Neutral (pin near a price)',
        volView: 'Falling',
        income: true,
        hedge: false,
        views: ['neutral', 'income', 'low-vol'],
        summary: 'Sell an ATM straddle and buy protective wings. Bigger credit than an iron condor but a narrower profit zone.',
        construction: ['Sell ATM call + ATM put', 'Buy OTM call + OTM put wings'],
        bestEnv: 'Stock pins near the short strikes at expiration.',
        worstEnv: 'A move past either wing.',
        advantages: ['Large upfront credit', 'Defined risk', 'Strong theta'],
        disadvantages: ['Narrow profit zone', 'Four legs', 'Needs price to sit still'],
        mistakes: ['Using on trending names', 'Wings too tight', 'Holding through a breakout'],
        assignment: 'Likely on a short strike at expiry if ITM.',
        timeDecay: 'Strongly positive.',
        related: ['iron-condor', 'short-straddle', 'butterfly-spread'],
        build: (s) => [
            { type: 'put', dir: 'long', strike: K(s, -0.1) },
            { type: 'put', dir: 'short', strike: K(s, 0) },
            { type: 'call', dir: 'short', strike: K(s, 0) },
            { type: 'call', dir: 'long', strike: K(s, 0.1) },
        ],
    },
    {
        slug: 'long-straddle',
        name: 'Long Straddle',
        difficulty: 'Intermediate',
        risk: 3,
        marketView: 'Big move, direction unknown',
        volView: 'Rising',
        income: false,
        hedge: false,
        views: ['high-vol'],
        summary: 'Buy an ATM call and an ATM put. Profits from a large move either way; loses if the stock sits still.',
        construction: ['Buy 1 ATM call', 'Buy 1 ATM put'],
        bestEnv: 'A binary event (earnings, ruling) that triggers a big move.',
        worstEnv: 'No move + IV crush after the event.',
        advantages: ['Profits from a move in either direction', 'Defined risk', 'Long volatility'],
        disadvantages: ['Expensive (two premiums)', 'IV crush after events', 'Needs a big move to pay off'],
        mistakes: ['Buying right before IV crush', 'Underestimating the move needed', 'Holding through theta'],
        assignment: 'None (you own both legs).',
        timeDecay: 'Strongly negative.',
        related: ['long-strangle', 'reverse-iron-condor'],
        build: (s) => [
            { type: 'call', dir: 'long', strike: K(s, 0) },
            { type: 'put', dir: 'long', strike: K(s, 0) },
        ],
    },
    {
        slug: 'short-straddle',
        name: 'Short Straddle',
        difficulty: 'Professional',
        risk: 5,
        marketView: 'Neutral (no move)',
        volView: 'Falling',
        income: true,
        hedge: false,
        views: ['low-vol', 'income', 'neutral'],
        summary: 'Sell an ATM call and put for a large credit. High income and theta, but undefined risk on both sides — for experienced traders only.',
        construction: ['Sell 1 ATM call', 'Sell 1 ATM put'],
        bestEnv: 'High IV that collapses while price barely moves.',
        worstEnv: 'A large move in either direction.',
        advantages: ['Large credit', 'Strong positive theta', 'Profits from IV contraction'],
        disadvantages: ['Undefined / unlimited risk', 'Margin intensive', 'Gap risk'],
        mistakes: ['Holding through earnings', 'No defined exit', 'Oversizing'],
        assignment: 'High — both short legs can be assigned.',
        timeDecay: 'Strongly positive.',
        related: ['short-strangle', 'iron-butterfly'],
        build: (s) => [
            { type: 'call', dir: 'short', strike: K(s, 0) },
            { type: 'put', dir: 'short', strike: K(s, 0) },
        ],
    },
    {
        slug: 'long-strangle',
        name: 'Long Strangle',
        difficulty: 'Intermediate',
        risk: 3,
        marketView: 'Big move, direction unknown',
        volView: 'Rising',
        income: false,
        hedge: false,
        views: ['high-vol'],
        summary: 'Buy an OTM call and an OTM put. Cheaper than a straddle but needs a bigger move to profit.',
        construction: ['Buy 1 OTM call', 'Buy 1 OTM put'],
        bestEnv: 'A very large move with expanding volatility.',
        worstEnv: 'Quiet, range-bound price.',
        advantages: ['Cheaper than a straddle', 'Long volatility', 'Defined risk'],
        disadvantages: ['Needs a bigger move', 'Time decay', 'Both legs can expire worthless'],
        mistakes: ['Strikes too far OTM', 'Buying after IV spikes', 'Too little time'],
        assignment: 'None (you own both legs).',
        timeDecay: 'Negative.',
        related: ['long-straddle', 'reverse-iron-condor'],
        build: (s) => [
            { type: 'call', dir: 'long', strike: K(s, 0.05) },
            { type: 'put', dir: 'long', strike: K(s, -0.05) },
        ],
    },
    {
        slug: 'short-strangle',
        name: 'Short Strangle',
        difficulty: 'Professional',
        risk: 5,
        marketView: 'Neutral (range-bound)',
        volView: 'Falling',
        income: true,
        hedge: false,
        views: ['low-vol', 'income', 'neutral'],
        summary: 'Sell an OTM call and put for a credit with a wider safe zone than a straddle — but still undefined risk.',
        construction: ['Sell 1 OTM call', 'Sell 1 OTM put'],
        bestEnv: 'Range-bound stock with high IV that falls.',
        worstEnv: 'A large move beyond a short strike.',
        advantages: ['Credit with a wide zone', 'Positive theta', 'Profits from IV drop'],
        disadvantages: ['Undefined risk', 'Margin intensive', 'Gap risk'],
        mistakes: ['Selling in low IV', 'No management plan', 'Oversizing'],
        assignment: 'High on a tested short strike.',
        timeDecay: 'Positive.',
        related: ['iron-condor', 'short-straddle'],
        build: (s) => [
            { type: 'call', dir: 'short', strike: K(s, 0.05) },
            { type: 'put', dir: 'short', strike: K(s, -0.05) },
        ],
    },
    {
        slug: 'butterfly-spread',
        name: 'Butterfly Spread',
        difficulty: 'Advanced',
        risk: 2,
        marketView: 'Neutral (pin near a price)',
        volView: 'Falling',
        income: false,
        hedge: false,
        views: ['neutral', 'low-vol', 'capital-efficient'],
        summary: 'Buy one lower call, sell two ATM calls, buy one higher call. Cheap, defined-risk bet that the stock pins the middle strike.',
        construction: ['Buy 1 lower call', 'Sell 2 ATM calls', 'Buy 1 higher call'],
        bestEnv: 'Stock sits right at the middle strike at expiration.',
        worstEnv: 'A move beyond either outer strike.',
        advantages: ['Low cost, high reward-to-risk', 'Defined risk', 'Great pin-the-price bet'],
        disadvantages: ['Narrow profit zone', 'Needs precise pricing', 'Four legs'],
        mistakes: ['Using on trending names', 'Entering too early', 'Ignoring fill quality'],
        assignment: 'Low until near expiry.',
        timeDecay: 'Positive near the body.',
        related: ['iron-butterfly', 'broken-wing-butterfly'],
        build: (s) => [
            { type: 'call', dir: 'long', strike: K(s, -0.1) },
            { type: 'call', dir: 'short', strike: K(s, 0), qty: 2 },
            { type: 'call', dir: 'long', strike: K(s, 0.1) },
        ],
    },
    {
        slug: 'broken-wing-butterfly',
        name: 'Broken Wing Butterfly',
        difficulty: 'Advanced',
        risk: 2,
        marketView: 'Neutral to mildly directional',
        volView: 'Falling',
        income: true,
        hedge: false,
        views: ['neutral', 'income'],
        summary: 'A butterfly with one wider wing, often opened for a credit so one side carries no risk.',
        construction: ['Buy 1 lower call', 'Sell 2 ATM calls', 'Buy 1 farther higher call'],
        bestEnv: 'Stock near the body with a directional lean to the safe side.',
        worstEnv: 'A move to the narrow-wing side.',
        advantages: ['Often a net credit', 'One side risk-free', 'Defined risk'],
        disadvantages: ['Skewed risk', 'Complex to manage', 'Four legs'],
        mistakes: ['Putting risk on the likely side', 'Bad fills', 'Sizing errors'],
        assignment: 'Low until near expiry.',
        timeDecay: 'Positive near the body.',
        related: ['butterfly-spread', 'jade-lizard'],
        build: (s) => [
            { type: 'call', dir: 'long', strike: K(s, -0.1) },
            { type: 'call', dir: 'short', strike: K(s, 0), qty: 2 },
            { type: 'call', dir: 'long', strike: K(s, 0.15) },
        ],
    },
    {
        slug: 'call-ratio-spread',
        name: 'Call Ratio Spread',
        difficulty: 'Advanced',
        risk: 5,
        marketView: 'Mildly bullish, capped',
        volView: 'Falling',
        income: true,
        hedge: false,
        views: ['neutral', 'income'],
        summary: 'Buy one call and sell two higher calls (often for a credit). Profits in a drift up to the short strikes, but carries unlimited upside risk.',
        construction: ['Buy 1 ATM call', 'Sell 2 higher OTM calls'],
        bestEnv: 'A slow grind up to the short strike.',
        worstEnv: 'A sharp rally far past the short strikes.',
        advantages: ['Often a credit', 'Cheap upside exposure', 'Profits in a measured move'],
        disadvantages: ['Unlimited risk above', 'Hard to manage', 'Not for beginners'],
        mistakes: ['Treating it as defined risk', 'Using on momentum names', 'Oversizing'],
        assignment: 'Possible on the extra short call.',
        timeDecay: 'Positive within the zone.',
        related: ['bull-call-spread', 'broken-wing-butterfly'],
        build: (s) => [
            { type: 'call', dir: 'long', strike: K(s, 0) },
            { type: 'call', dir: 'short', strike: K(s, 0.1), qty: 2 },
        ],
    },
    {
        slug: 'jade-lizard',
        name: 'Jade Lizard',
        difficulty: 'Advanced',
        risk: 4,
        marketView: 'Neutral to bullish',
        volView: 'Falling',
        income: true,
        hedge: false,
        views: ['neutral', 'income', 'bullish'],
        summary: 'Sell a put and sell a call spread, sized so the total credit exceeds the call-spread width — leaving no upside risk.',
        construction: ['Sell 1 OTM put', 'Sell 1 OTM call', 'Buy 1 higher call'],
        bestEnv: 'High IV, neutral-to-bullish, that contracts.',
        worstEnv: 'A sharp drop (downside is the real risk).',
        advantages: ['No risk to the upside', 'Strong credit', 'Positive theta'],
        disadvantages: ['Large downside risk on the put', 'Three legs', 'Assignment risk'],
        mistakes: ['Credit smaller than the call width', 'Ignoring downside sizing', 'Earnings surprises'],
        assignment: 'Possible on the short put or call.',
        timeDecay: 'Positive.',
        related: ['cash-secured-put', 'bear-call-spread'],
        build: (s) => [
            { type: 'put', dir: 'short', strike: K(s, -0.05) },
            { type: 'call', dir: 'short', strike: K(s, 0.05) },
            { type: 'call', dir: 'long', strike: K(s, 0.12) },
        ],
    },
    {
        slug: 'reverse-iron-condor',
        name: 'Reverse Iron Condor',
        difficulty: 'Advanced',
        risk: 3,
        marketView: 'Big move, direction unknown',
        volView: 'Rising',
        income: false,
        hedge: false,
        views: ['high-vol', 'capital-efficient'],
        summary: 'Buy a put spread and a call spread — a defined-risk, cheaper way to bet on a big move (the debit cousin of the iron condor).',
        construction: ['Buy OTM put + sell lower put', 'Buy OTM call + sell higher call'],
        bestEnv: 'A large move out of a range, IV expanding.',
        worstEnv: 'Stock pins inside the inner strikes.',
        advantages: ['Defined risk', 'Cheaper than a strangle', 'Profits on a breakout either way'],
        disadvantages: ['Capped profit', 'Needs a real move', 'Four legs'],
        mistakes: ['Inner strikes too wide', 'Buying after IV spikes', 'Too little time'],
        assignment: 'Low (short legs are protected).',
        timeDecay: 'Negative.',
        related: ['long-strangle', 'iron-condor'],
        build: (s) => [
            { type: 'put', dir: 'long', strike: K(s, -0.05) },
            { type: 'put', dir: 'short', strike: K(s, -0.15) },
            { type: 'call', dir: 'long', strike: K(s, 0.05) },
            { type: 'call', dir: 'short', strike: K(s, 0.15) },
        ],
    },
    {
        slug: 'synthetic-long',
        name: 'Synthetic Long Stock',
        difficulty: 'Advanced',
        risk: 4,
        marketView: 'Bullish',
        volView: 'Neutral',
        income: false,
        hedge: false,
        views: ['bullish', 'capital-efficient'],
        summary: 'Buy a call and sell a put at the same strike to replicate long stock with far less capital — and the full downside.',
        construction: ['Buy 1 ATM call', 'Sell 1 ATM put'],
        bestEnv: 'A clear bullish view where capital efficiency matters.',
        worstEnv: 'A decline — losses mirror owning the stock.',
        advantages: ['Stock-like payoff', 'Very capital efficient', 'Little time-decay drag'],
        disadvantages: ['Full downside risk', 'Margin + assignment risk', 'No dividends'],
        mistakes: ['Forgetting it behaves like 100 shares', 'Underestimating margin', 'Oversizing'],
        assignment: 'Yes — the short put can be assigned.',
        timeDecay: 'Roughly neutral.',
        related: ['synthetic-short', 'long-call'],
        build: (s) => [
            { type: 'call', dir: 'long', strike: K(s, 0) },
            { type: 'put', dir: 'short', strike: K(s, 0) },
        ],
    },
    {
        slug: 'synthetic-short',
        name: 'Synthetic Short Stock',
        difficulty: 'Advanced',
        risk: 5,
        marketView: 'Bearish',
        volView: 'Neutral',
        income: false,
        hedge: false,
        views: ['bearish', 'capital-efficient'],
        summary: 'Sell a call and buy a put at the same strike to replicate short stock — capital efficient, with unlimited upside risk.',
        construction: ['Sell 1 ATM call', 'Buy 1 ATM put'],
        bestEnv: 'A clear bearish view without borrowing shares.',
        worstEnv: 'A rally — losses mirror a short position.',
        advantages: ['Short-like payoff', 'Capital efficient', 'No share borrow needed'],
        disadvantages: ['Unlimited upside risk', 'Margin + assignment risk', 'Hard to manage'],
        mistakes: ['Underestimating risk', 'Oversizing', 'No stop plan'],
        assignment: 'Yes — the short call can be assigned.',
        timeDecay: 'Roughly neutral.',
        related: ['synthetic-long', 'long-put'],
        build: (s) => [
            { type: 'call', dir: 'short', strike: K(s, 0) },
            { type: 'put', dir: 'long', strike: K(s, 0) },
        ],
    },
    {
        slug: 'poor-mans-covered-call',
        name: "Poor Man's Covered Call",
        difficulty: 'Advanced',
        risk: 3,
        marketView: 'Bullish (income)',
        volView: 'Neutral to falling',
        income: true,
        hedge: false,
        views: ['bullish', 'income', 'capital-efficient'],
        summary: 'Replace the 100 shares of a covered call with a deep-ITM long-dated call (LEAPS), then sell shorter calls against it for income.',
        construction: ['Buy 1 deep-ITM long-dated call (stock proxy)', 'Sell 1 shorter OTM call'],
        bestEnv: 'Slow grind up on a stock you want leveraged income from.',
        worstEnv: 'A sharp drop hits the long call harder than shares would.',
        advantages: ['Covered-call income for far less capital', 'Defined risk', 'Capital efficient'],
        disadvantages: ['Long call decays (a diagonal, not a true covered call)', 'No dividends', 'Roll management needed'],
        mistakes: ['Long call not deep/long enough', 'Short strike below long-call cost', 'Ignoring the diagonal time risk'],
        assignment: 'Possible on the short call.',
        timeDecay: 'Mixed — short leg positive, long leg negative.',
        related: ['covered-call', 'bull-call-spread'],
        build: (s) => [
            { type: 'call', dir: 'long', strike: K(s, -0.2) },
            { type: 'call', dir: 'short', strike: K(s, 0.05) },
        ],
    },
    {
        slug: 'box-spread',
        name: 'Box Spread',
        difficulty: 'Professional',
        risk: 1,
        marketView: 'None (financing / arbitrage)',
        volView: 'None',
        income: false,
        hedge: false,
        views: ['capital-efficient'],
        summary: 'A bull call spread plus a bear put spread at the same strikes — a near risk-free position used for financing or locking an arbitrage. Edge is tiny and pricing-sensitive.',
        construction: ['Bull call spread', '+ Bear put spread (same strikes)'],
        bestEnv: 'Capturing a small rate/financing edge with locked payoff.',
        worstEnv: 'Fees/early assignment erase the thin edge.',
        advantages: ['Payoff locked at expiry', 'Minimal market risk', 'Cash-management tool'],
        disadvantages: ['Tiny edge', 'Fees can erase it', 'American-style assignment risk'],
        mistakes: ['Ignoring assignment risk', 'Underpricing fees', 'Using illiquid strikes'],
        assignment: 'Material with American options — a known box-spread hazard.',
        timeDecay: 'Negligible (locked).',
        related: ['bull-call-spread', 'bear-put-spread'],
        build: (s) => [
            { type: 'call', dir: 'long', strike: K(s, 0) },
            { type: 'call', dir: 'short', strike: K(s, 0.1) },
            { type: 'put', dir: 'long', strike: K(s, 0.1) },
            { type: 'put', dir: 'short', strike: K(s, 0) },
        ],
    },
    {
        slug: 'calendar-spread',
        name: 'Calendar Spread',
        difficulty: 'Advanced',
        risk: 2,
        marketView: 'Neutral near the strike',
        volView: 'Rising (back month)',
        income: false,
        hedge: false,
        views: ['neutral', 'low-vol'],
        noPayoff: true,
        summary: 'Sell a near-dated option and buy a longer-dated one at the same strike. Profits from faster decay in the front month and rising back-month IV. (A time spread — its payoff depends on two expirations, so no single-expiry diagram is shown.)',
        construction: ['Sell 1 near-dated option', 'Buy 1 longer-dated option (same strike)'],
        bestEnv: 'Stock near the strike with rising longer-term IV.',
        worstEnv: 'A big move away from the strike.',
        advantages: ['Profits from time-decay differential', 'Defined risk (the debit)', 'Long back-month vega'],
        disadvantages: ['Needs price near the strike', 'Two expirations to manage', 'IV-path dependent'],
        mistakes: ['Ignoring the back-month IV', 'Strike too far from price', 'Mismanaging the roll'],
        assignment: 'Possible on the short near-dated leg.',
        timeDecay: 'Positive (front decays faster than back).',
        related: ['diagonal-spread', 'poor-mans-covered-call'],
        build: () => [],
    },
    {
        slug: 'diagonal-spread',
        name: 'Diagonal Spread',
        difficulty: 'Advanced',
        risk: 2,
        marketView: 'Directional + time',
        volView: 'Neutral to rising (back month)',
        income: true,
        hedge: false,
        views: ['bullish', 'income'],
        noPayoff: true,
        summary: 'A calendar with different strikes — combining a directional lean with time-decay capture. (A time spread across two expirations, so no single-expiry diagram is shown.)',
        construction: ['Sell 1 near-dated option', 'Buy 1 longer-dated option (different strike)'],
        bestEnv: 'A slow directional drift with a stable-to-rising back-month IV.',
        worstEnv: 'A fast move against the position.',
        advantages: ['Directional + theta capture', 'Capital efficient', 'Flexible'],
        disadvantages: ['Two expirations', 'IV-path dependent', 'Roll management'],
        mistakes: ['Over-wide strikes', 'Ignoring vega', 'Poor roll discipline'],
        assignment: 'Possible on the short near-dated leg.',
        timeDecay: 'Generally positive front-month.',
        related: ['calendar-spread', 'poor-mans-covered-call'],
        build: () => [],
    },
];

export const STRATEGY_BY_SLUG: Record<string, Strategy> = Object.fromEntries(
    STRATEGIES.map((s) => [s.slug, s])
);

export const VIEW_LABELS: { id: View; label: string }[] = [
    { id: 'bullish', label: 'Bullish' },
    { id: 'bearish', label: 'Bearish' },
    { id: 'neutral', label: 'Neutral' },
    { id: 'high-vol', label: 'High Volatility' },
    { id: 'low-vol', label: 'Low Volatility' },
    { id: 'income', label: 'Income' },
    { id: 'hedging', label: 'Hedging' },
    { id: 'capital-efficient', label: 'Capital Efficient' },
];
