'use client';

import { useState } from 'react';
import { Sparkles, Loader2, AlertCircle } from 'lucide-react';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from '@/components/ui/dialog';
import {
    explainIndicator,
    type IndicatorExplanation,
} from '@/lib/actions/ai.actions';
import { useIsAuthed } from '@/components/AuthProvider';
import { SIGN_IN_URL } from '@/lib/constants';

const SECTIONS: Array<{ key: keyof IndicatorExplanation; label: string }> = [
    { key: 'summary', label: 'What it measures' },
    { key: 'importance', label: 'Why it matters' },
    { key: 'watch', label: 'What to watch for' },
    { key: 'when', label: 'When to use it' },
];

type State =
    | { status: 'idle' }
    | { status: 'loading' }
    | { status: 'ready'; data: IndicatorExplanation }
    | { status: 'error'; error: string };

/**
 * AI button on each indicator card. On first open it asks the LLM to explain
 * the indicator in plain language, then keeps the result so re-opening is instant.
 */
export default function IndicatorExplainButton({
    name,
    blurb,
    category,
}: {
    name: string;
    blurb: string;
    category?: string;
}) {
    const [state, setState] = useState<State>({ status: 'idle' });
    const isAuthed = useIsAuthed();

    // Public page, members-only AI: anonymous visitors get a sign-in link in
    // place of the Explain button (the action is gated server-side too).
    if (!isAuthed) {
        return (
            <a
                href={SIGN_IN_URL}
                title="Sign in to explain this indicator with AI"
                aria-label={`Sign in to explain ${name} with AI`}
                className="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-md border border-teal-500/30 bg-teal-500/10 text-teal-300 transition-colors hover:bg-teal-500/20 hover:text-teal-200"
            >
                <Sparkles className="h-4 w-4" />
            </a>
        );
    }

    async function load() {
        setState({ status: 'loading' });
        const res = await explainIndicator(name, blurb, category);
        if (res.ok) {
            setState({ status: 'ready', data: res.data });
        } else {
            setState({ status: 'error', error: res.error });
        }
    }

    function onOpenChange(open: boolean) {
        // Fetch the first time the dialog is opened (unless we already have it).
        if (open && state.status !== 'ready' && state.status !== 'loading') {
            void load();
        }
    }

    return (
        <Dialog onOpenChange={onOpenChange}>
            <DialogTrigger asChild>
                <button
                    type="button"
                    title="Explain this indicator with AI"
                    aria-label={`Explain ${name} with AI`}
                    className="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-md border border-teal-500/30 bg-teal-500/10 text-teal-300 transition-colors hover:bg-teal-500/20 hover:text-teal-200"
                >
                    <Sparkles className="h-4 w-4" />
                </button>
            </DialogTrigger>

            <DialogContent className="max-h-[85vh] overflow-y-auto border-gray-800 bg-gray-950">
                <DialogHeader>
                    <DialogTitle className="flex items-center gap-2 text-gray-100">
                        <Sparkles className="h-4 w-4 text-teal-400" />
                        {name}
                    </DialogTitle>
                    <DialogDescription className="text-gray-500">
                        A plain-language explainer generated by AI — educational only, not advice.
                    </DialogDescription>
                </DialogHeader>

                {state.status === 'loading' && (
                    <div className="flex items-center gap-2 py-8 text-sm text-gray-400">
                        <Loader2 className="h-4 w-4 animate-spin text-teal-400" />
                        Thinking through this indicator…
                    </div>
                )}

                {state.status === 'error' && (
                    <div className="flex flex-col items-start gap-3 py-4">
                        <div className="flex items-start gap-2 text-sm text-yellow-200/80">
                            <AlertCircle className="mt-0.5 h-4 w-4 shrink-0 text-yellow-400/80" />
                            <span>{state.error}</span>
                        </div>
                        <button
                            type="button"
                            onClick={() => void load()}
                            className="rounded-md border border-gray-700 px-3 py-1.5 text-sm text-gray-200 transition-colors hover:bg-gray-800"
                        >
                            Try again
                        </button>
                    </div>
                )}

                {state.status === 'ready' && (
                    <div className="flex flex-col gap-4 py-1">
                        {SECTIONS.map(({ key, label }) => (
                            <div key={key} className="flex flex-col gap-1">
                                <h4 className="text-xs font-semibold uppercase tracking-wide text-teal-400">
                                    {label}
                                </h4>
                                <p className="text-sm leading-relaxed text-gray-300">
                                    {state.data[key]}
                                </p>
                            </div>
                        ))}
                    </div>
                )}
            </DialogContent>
        </Dialog>
    );
}
